### ISSUE TITLE
The latest and all route is not working on the API server

### ISSUE THREAD

**Issue by altezza04** [ExpDev07/coronavirus-tracker-api#1]
The latest and all route is not working on the API server

https://coronavirus-tracker-api.herokuapp.com/latest
https://coronavirus-tracker-api.herokuapp.com/all

Thanks!

**Comment by ExpDev07** [comment]
I am working on ``/all`` now, which will replace ``/latest``.

**Comment by ExpDev07** [comment]
Added now, also added a total to the other endpoints and countries are now nested under locations.

Current endpoints:
https://coronavirus-tracker-api.herokuapp.com/confirmed
https://coronavirus-tracker-api.herokuapp.com/deaths
https://coronavirus-tracker-api.herokuapp.com/recovered

For all of them combined:
https://coronavirus-tracker-api.herokuapp.com/all
