### ISSUE TITLE
Allow more parameters beyond 2 letter country code

### ISSUE THREAD

**Issue by shaunlawrencecarland** [ExpDev07/coronavirus-tracker-api#105]
Would it be possible to expand the API to take in more than a 2 letter country code?  Being able to put in a 3 letter country code would be great for me, or being able to just put in the name of the country.

**Comment by ExpDev07** [comment]
The name of the country I can do, however, ATM, there’s no support for 3-letter country codes.

**Comment by shaunlawrencecarland** [comment]
@ExpDev07 thanks so much!

**Comment by ExpDev07** [comment]
Possible through https://github.com/ExpDev07/coronavirus-tracker-api/pull/122. You can now filter by any field, e.g filtering county with CSBS source: ``https://coronavirus-tracker-api.herokuapp.com/v2/locations?source=csbs&county=Montgomery``.
