### ISSUE TITLE
United Kingdom (GB) isn't updated

### ISSUE THREAD

**Issue by TGamingStudio** [ExpDev07/coronavirus-tracker-api#109]
https://coronavirus-tracker-api.herokuapp.com/v2/locations?country_code=gb
Returns `"latest":{"confirmed":10,"deaths":0,"recovered":2}`

**Comment by ExpDev07** [comment]
It returns multiple locations within GB. For example, https://coronavirus-tracker-api.herokuapp.com/v2/locations/2 shows 3983, 177, and 65. You need to sum them all together if you want the latest of the country, Great Britain.

**Comment by TGamingStudio** [comment]
Thank you, this fixes that issue, I haven't noticed that
