### ISSUE TITLE
About differences between repository and John Hopking Data

### ISSUE THREAD

**Issue by Lopez-ivan** [ExpDev07/coronavirus-tracker-api#124]
Hey! Good job with this API.

Do anyone knows why the lastest info (Confirmated) in the repository is different than the info shown in the John Hopkins CSSE app? The information comes from the same place, right?

Examples: Today this API shows that Argentina, Chile, and Brazil have 128, 434 and 793 confirmed cases while in the CSSE shows 158, 537 and 977.

**Comment by ExpDev07** [comment]
You would think so, but they actually don’t. I believe the CSV files are generated from the dashboard and not wise versa, and it’s done once a day at some time stamp.
