### ISSUE TITLE
See country total instead of province.

### ISSUE THREAD

**Issue by yachtSamba** [ExpDev07/coronavirus-tracker-api#129]
I don't know if I'm just missing it, but I can't seem to find a query parameter that returns the latest cases per country, instead of per province, as is currently the case. Is the only possibility at the moment to go through each province belonging to a country and to add the total cases together?

Thanks

**Comment by ExpDev07** [comment]
There is a PR open right now addressing this (https://github.com/ExpDev07/coronavirus-tracker-api/pull/122). You can do it yourself for now though. Simply get your country (e.g U.S: ``/v2/locations?country_code=US``, then sum the latest of all the locations returned together (aggregation). That'll yield your result. It's a really simple process and like I said, once the PR is merged, the API will do this for you.

**Comment by yachtSamba** [comment]
Thanks, that's what I thought, and that's what I've been doing :).  Any idea when the PR will merged?

**Comment by ExpDev07** [comment]
@yachtSamba depends when the guy gets back to me. If not, I'll just add it myself.

**Comment by yachtSamba** [comment]
Ok thanks

**Comment by yachtSamba** [comment]
Has it been added, seeing you closed the issue?  I can't find the query parameter.

**Comment by ExpDev07** [comment]
Latest for U.S: ``https://coronavirus-tracker-api.herokuapp.com/v2/locations?country_code=US``, then see the ``latest`` top-level JSON object.

**Comment by yachtSamba** [comment]
Oh ok thank you. I wasn't sure if that was right as the numbers were significantly lower than on other sources, but on #113 I see that it's because JHU only update daily. Thank you.

**Comment by ExpDev07** [comment]
You can try an alternative source like ``/v2/locations?country_code=US&source=csbs`` (from https://www.csbs.org/information-covid-19-coronavirus), but unfortunately, they don't provide recoveries at all.

**Comment by yachtSamba** [comment]
Thank you, but they don't seem to provide data for countries other than the US, so that's also a non-starter for me :). I love what you've made though!

**Comment by ExpDev07** [comment]
Planning to add more datasources.
