### ISSUE TITLE
Keep API and format stable and consider adding Time Updated

### ISSUE THREAD

**Issue by pizzavore** [ExpDev07/coronavirus-tracker-api#13]
First off, thanks for creating this API! It's very useful.

As I believe many people are now using this, I hope you keep the API and format stable, i.e. no breaking changes, such as changing the format of the dates, etc.  

If you do see a need to make a breaking change, please consider adding separate endpoint URIs, such as with a version in the path or something.

Also, as a non-breaking change, is it possible to add a a top-level field to note the time the data was updated / processed in ISO format?  Perhaps like this:

{
 "confirmed": ...
 "deaths": ...
 "latest": ...
 "recovered": ...
 "source": ...
 "updated": "2020-03-06T10:38:20.577Z"
}

Thanks again!

**Comment by ExpDev07** [comment]
Thanks! Yes, there are quite a few people using the API. If breaking changes are coming, they’ll be added under a separate URL (e.g /v2/all). The last updated is a good idea.

**Comment by ExpDev07** [comment]
Added per https://github.com/ExpDev07/coronavirus-tracker-api/pull/18.
