### ISSUE TITLE
Consider switching (from Flask) to ASGI framework

### ISSUE THREAD

**Issue by Kilo59** [ExpDev07/coronavirus-tracker-api#130]
Have you considered switching to one of the newer ASGI based web frameworks?

I would like to recommend [FastAPI](https://fastapi.tiangolo.com/)

Among other things, I believe this project would greatly benefit from these features.

1. [Automatic Swagger/OpenAPI API documentation tools](https://fastapi.tiangolo.com/#interactive-api-docs) (and [ReDoc](https://github.com/Redocly/redoc))
2. [Handle more simultaneous request](https://fastapi.tiangolo.com/#performance). [Benchmarks](https://www.techempower.com/benchmarks/#section=test&runid=7464e520-0dc2-473d-bd34-dbdfd7e85911&hw=ph&test=query&l=zijzen-7)
3. Ease of development

I would be happy to work on this if it's something you think the project could benefit from.

https://fastapi.tiangolo.com/alternatives/
https://fastapi.tiangolo.com/advanced/wsgi/

**Comment by ExpDev07** [comment]
Looks interesting.

**Comment by Kilo59** [comment]
![image](https://user-images.githubusercontent.com/13108583/77239328-12ad8800-6bb0-11ea-963a-3fadac25cd6c.png)

**Comment by ExpDev07** [comment]
Looks nice!

**Comment by Kilo59** [comment]
For the initial switchover I'm going to attempt to keep the exact same shape of `v2`. As such I've created data models (for use as [Response Models](https://fastapi.tiangolo.com/tutorial/response-model/)) based on the existing `Location`, `TimelinedLocation`, `Timeline` classes as well as the shape of the currently returned JSON.

Here's some more details about 
https://fastapi.tiangolo.com/tutorial/response-model/

```python
class Totals(pydantic.BaseModel):
    confirmed: int
    deaths: int
    recovered: int


class Latest(pydantic.BaseModel):
    latest: Totals


class TimelineStats(pydantic.BaseModel):
    latest: int
    timeline: Dict[str, int]


class TimelinedLocation(pydantic.BaseModel):
    confirmed: TimelineStats
    deaths: TimelineStats
    recovered: TimelineStats


class Country(pydantic.BaseModel):
    coordinates: Dict
    country: str
    country_code: str
    id: int
    last_updated: dt.datetime
    latest: Totals
    province: str = ""
    timelines: TimelinedLocation
```

**Comment by ExpDev07** [comment]
Great job

**Comment by mustaphee** [comment]
Although I feel it might not really be needed to switch Framework, however,  if you decide to use FastAPI, I would gladly assist to with it.

**Comment by ExpDev07** [comment]
@mustaphee the code really isn't *that* advanced yet, so a framework switch wouldn't be the biggest deal given it provides benefits, which it looks like it very much does. We can just see how it turns out, if I'm happy with it and it's compatible with the current endpoints (so not to break apps using it), I'll merge.
