### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by gianpaolof** [ExpDev07/coronavirus-tracker-api#139]
hi
I can't seem to be able to call:
/v2/locations/:id
it always returns 404
can you give me an example of a request with full path?

Thanks

**Comment by itsamirrezah** [comment]
Hi @gianpaolof 

for example you can test this request: 
https://coronavirus-tracker-api.herokuapp.com/v2/locations/39

**Comment by gianpaolof** [comment]
oh, i was keep on trying with the ":"
thanks
