### ISSUE TITLE
Adding country codes

### ISSUE THREAD

**Issue by Bost** [ExpDev07/coronavirus-tracker-api#14]
Would you be interested in adding [ISO_3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) alpha-2 or alpha-3 country codes? E.g. extending:
```json
"coordinates" : "{...}"
"country"  "Mainland China"
"history" : "{...}"
"latest" : 990
"province" : "Anhui"
```
by
```json
"alpha-2 code" : "CN" 
"alpha-3 code" : "CHN" 
```
My telegram bot https://t.me/corona_cases_bot needs it, and I consider what is better - implemented in mine or your project?

**Comment by ExpDev07** [comment]
Would be beneficial to also allow querying the API for specific countries. Would both codes be neccecary or should we go with only one??

**Comment by Bost** [comment]
Just alpha-2 should be probably enough. alpha-2's are unambiguous so an additional translation to alpha-3 is trivial. And also less data transferred means faster API service.

**Comment by ExpDev07** [comment]
The last issue I guess would be to figure out how to pull the country codes as JSU doesn't offer them. I'm guessing the best solution would be to hard-code them into a map ("Mainland China" => "CN").
