### ISSUE TITLE
We are using this API for COVID-19 Badges

### ISSUE THREAD

**Issue by codedawi** [ExpDev07/coronavirus-tracker-api#142]
![Cases](https://covid19-badges.herokuapp.com/confirmed) ![Deaths](https://covid19-badges.herokuapp.com/deaths) ![Recovered](https://covid19-badges.herokuapp.com/recovered)

Using this data to populate the count information for `cases`, `deaths`, and `recovered` badges so people can easily see the most up to data from readme.md of all these great repos working on `COVID-19`.

url: `https://covid19-badges.herokuapp.com/<confirmed|deaths|recovered>/latest` 
repo: `https://github.com/fight-covid19/bagdes`

**Comment by ExpDev07** [comment]
Would be awesome if you can open a PR request and add these to our README 😎  (feel free to have them link to your github repo)!

**Comment by ExpDev07** [comment]
Nvm, I opened one :) https://github.com/ExpDev07/coronavirus-tracker-api/pull/144. Thanks for this!
