### ISSUE TITLE
Add API endpoint to see available sources to choose from.

### ISSUE THREAD

**Issue by jdeweese1** [ExpDev07/coronavirus-tracker-api#148]
While working on the Python [wrapper](https://github.com/Kamaropoulos/COVID19Py/issues/7) for this API, we were updating the code to be able to decide which service to pull data from (jhu,csbs, etc) we decided it would be advantageous if we could query an url endpoint to get a list of valid sources.

see [COVID19Py](https://github.com/Kamaropoulos/COVID19Py/issues/7) for more details

(on mobile so I apologize for the formatting)

**Comment by ExpDev07** [comment]
https://github.com/ExpDev07/coronavirus-tracker-api/pull/149

**Comment by ExpDev07** [comment]
Available sources can now be found at https://coronavirus-tracker-api.herokuapp.com/v2/sources.

**Comment by Kamaropoulos** [comment]
Thanks a lot @ExpDev07, you're awesome!
