### ISSUE TITLE
US Recovery data missing

### ISSUE THREAD

**Issue by mmilosanovic** [ExpDev07/coronavirus-tracker-api#152]
It seems CSSEGISandData started (on 3/18/20) providing the recovery cases data at high level only (country = US and province = US). This data seems to be missing on the API response.

**Comment by ExpDev07** [comment]
Duplicate of https://github.com/ExpDev07/coronavirus-tracker-api/issues/113. I was hoping JHU would fix this soon. Currently working on adding additional sources.

**Comment by mmilosanovic** [comment]
Perfect. Thanks for providing this API, it is very useful to help track the impacts on operations.
