### ISSUE TITLE
Hello! Thanks for creating this useful API!

### ISSUE THREAD

**Issue by TheAleLoco2** [ExpDev07/coronavirus-tracker-api#154]
I create an app to show statistics and I will improve it over time. The link is https://play.google.com/store/apps/details?id=com.cthulhu.covidtracker

**Comment by Kilo59** [comment]
Getting a 404 for this. Do you have an updated URL?

**Comment by TheAleLoco2** [comment]
> Getting a 404 for this. Do you have an updated URL?

Google just deleted my app, is very sensitive to this issue.
