### ISSUE TITLE
JHU data won't be updated

### ISSUE THREAD

**Issue by tctree333** [ExpDev07/coronavirus-tracker-api#155]
Hello!
I'm using your API to fetch data for a discord bot, and as I was looking through the code, I noticed that the source for JHU data isn't going to be updated anymore per a recent update.
(https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series)

You may want to update the code to use the new files.

**Comment by chovy** [comment]
Yes, please do update. Nice catch. I rely heavily on this API

**Comment by ExpDev07** [comment]
I will be updating it. Seems like they're not going to be supporting recoveries anymore either.

**Comment by chovy** [comment]
How is NYT getting that USA map updated with county data?

**Comment by ExpDev07** [comment]
@chovy could be an internal source. If you want county data, you can use the CSBS source recently added at https://coronavirus-tracker-api.herokuapp.com/v2/locations?source=csbs.

**Comment by chovy** [comment]
Is this county data only for USA?

**Comment by ExpDev07** [comment]
Yes, CSBS is U.S. specifically. @chovy

**Comment by chovy** [comment]
ALso I was using /all before. WHich endpint should i use now?

**Comment by chovy** [comment]
https://coronavirus-tracker-api.herokuapp.com/v2/locations is this same as /all ?

**Comment by ExpDev07** [comment]
@chovy Yes, you should use the locations endpoint. It's the same as /all, just the confirmed and deaths are in the same location object and not in different.

**Comment by chovy** [comment]
Sorry I don't understand.

**Comment by ExpDev07** [comment]
Look in the README and you'll see example responses :) @chovy

**Comment by chovy** [comment]
Awesome thanks. updated my map! https://virusoutbreak.wtf

**Comment by ExpDev07** [comment]
JHU source updated. See details here: https://github.com/ExpDev07/coronavirus-tracker-api/pull/156. Also, @chovy, it would really be appreciated but don't in any way feel obligated to :). My BTC address is ``bc1qy6e8d9laqnuwm5vyd87y47z0cu9vw76cj4ejd3``.
