### ISSUE TITLE
Incorrect recovered latest data.

### ISSUE THREAD

**Issue by Cyrusrome22** [ExpDev07/coronavirus-tracker-api#158]
I have noticed that there is a mismatch for some countries.

https://coronavirus-tracker-api.herokuapp.com/v2/locations

For example:
**Maldives**
{"coordinates":{"latitude":"3.2028","longitude":"73.2207"},"country":"Maldives","country_code":"MV","id":154,"last_updated":"2020-03-24T05:07:57.390150Z","latest":{**"confirmed":13,"**deaths":0,**"recovered":59879**},"province":""}

**Hubei**
{"coordinates":{"latitude":"30.9756","longitude":"112.2707"},"country":"China","country_code":"CN","id":62,"last_updated":"2020-03-24T05:07:57.025962Z","latest":{**"confirmed":67800**,"deaths":3153,**"recovered":1**},"province":"Hubei"}

**Comment by ExpDev07** [comment]
You are indeed correct. Looks like we have to drop support for recoveries in /v2/ for JHU.

**Comment by ExpDev07** [comment]
https://github.com/ExpDev07/coronavirus-tracker-api/pull/156
