### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by altezza04** [ExpDev07/coronavirus-tracker-api#16]
It seem server is down https://coronavirus-tracker-api.herokuapp.com/all 500 internal error

**Comment by ronaldaug** [comment]
Same here "Internal Server Error".

**Comment by Omaroid** [comment]
Same

**Comment by ExpDev07** [comment]
Looking into it.

**Comment by ExpDev07** [comment]
Issue has been resolved. Thanks for reporting!
