### ISSUE TITLE
Thanks a lot for providing this API!

### ISSUE THREAD

**Issue by davidsommer** [ExpDev07/coronavirus-tracker-api#160]
I created a small Chart that consumes your API, you can find the code here: https://github.com/davidsommer/coronaCharts and the displayed data here https://davidsommer.github.io/coronaCharts/

**Comment by ExpDev07** [comment]
Nice work!

**Comment by jonmancia** [comment]
@ExpDev07 Do we get access to the previous version of the api? The recent changes broke my app :(

**Comment by ExpDev07** [comment]
@jonmancia There shouldn't be any breaking changes except from the fact that recoveries return 0 and there's no timeline available for it? These endpoints are still available:

* https://coronavirus-tracker-api.herokuapp.com/all
* https://coronavirus-tracker-api.herokuapp.com/confirmed
* https://coronavirus-tracker-api.herokuapp.com/deaths
* https://coronavirus-tracker-api.herokuapp.com/recovered (doesn't show updated)

**Comment by jonmancia** [comment]
> @jonmancia There shouldn't be any breaking changes except from the fact that recoveries return 0 and there's no timeline available for it? These endpoints are still available:
> 
> * https://coronavirus-tracker-api.herokuapp.com/all
> * https://coronavirus-tracker-api.herokuapp.com/confirmed
> * https://coronavirus-tracker-api.herokuapp.com/deaths
> * https://coronavirus-tracker-api.herokuapp.com/recovered (doesn't show updated)

The problem I had was accessing the states/provinces for a given country. But I noticed appending `?source=csbs` returns locations again

**Comment by ExpDev07** [comment]
Ohh yeah, you can’t go back to that version no... unfortunately. JHU changed their directory structure and decided to leave out states with their new files. @jonmancia

**Comment by jonmancia** [comment]
That is really sad! I have to change my entire app now. Thanks for your swift response regardless

**Comment by ExpDev07** [comment]
@jonmancia it is. Despite being regarded as one of the top sources for this outbreak, JHU decides to pull unexpected changes like these in the middle of it.
