### ISSUE TITLE
Location IDs have changed

### ISSUE THREAD

**Issue by brunobord** [ExpDev07/coronavirus-tracker-api#162]
Hello,

First of all, thank you for making this very valuable resource available online, it's important to give access to raw data to everyone.

Now, I'd like to mention a curious change in the resource IDs. Last time I've checked (it was on Friday, March 20th), the ID of metropolitan France was `157`. Today (March 24th), this ID points at Mauritius (country code MU).

1. How did that happen? Was this change expected?
2. That's disturbing, it means that there's no way to build a query to precisely fetch data related to a location. Using country code is not enough, because giving `country_code=FR` would also return overseas territories, which makes the extraction a bit harder.

So what would be the future of this API? Would IDs be subject to change and we would have to target a precise location using other means that the ID? or would we expect these IDs to settle?

Regards.

**Comment by ExpDev07** [comment]
The IDs definitively were not meant to change and was an effect of our data-provider unexpectedly changing their indexes as part of a restructuring. So for now they’ll stay until they change again, which hopefully won’t happen. I’m working on getting the data into a database so the IDs can stay persistent.

**Comment by brunobord** [comment]
thank you for the quick response.
Acknowledging that the issue is handled :o)
Keep up the good work!
