### ISSUE TITLE
Inconsistent country results

### ISSUE THREAD

**Issue by lovelaced** [ExpDev07/coronavirus-tracker-api#164]
Hi,
Thanks for doing this. I was looking for this exact type of project for a bot I was requested to write. :) So far, everything has worked pretty well. There are a couple problems with the consistency of the data that I've noticed, though.

1) Countries with provinces/states/sub-areas don't have their own ID/timeline. This was changed for the US query yesterday; the US now has a timeline and ID, but no longer has states.

2) The structure of sub-states/provinces for countries seems inconsistent. For example, when I request the country page for Canada, it lists all the provinces so I can easily query the ID from one of the provinces directly from that JSON and get an individual provincial timeline. However, the country page for the US now doesn't show all the states as it did before, so I can't just get the USA JSON if I want to query a state - am I understanding correctly I'd have to pull the entire `/locations`? I'd like to avoid making large queries if possible, and this seems inconsistent.

Thanks!

**Comment by imjoshellis** [comment]
FYI, this is inconsistent at the source, making it a source-level issue. The source changed their data structure for US as a special case. [@CSSEGISandData/COVID-19](https://github.com/CSSEGISandData/COVID-19) accumulated over 100 new issues overnight because of this dramatic change...

**Comment by lovelaced** [comment]
Thanks for the info. I imagine it'll probably happen again, then. Closing due to not a problem with upstream :)
