### ISSUE TITLE
Add CONTRIBUTION guideline

### ISSUE THREAD

**Issue by gribok** [ExpDev07/coronavirus-tracker-api#169]
Add CONTRIBUTION guideline for improved collaboration in the open source project. It enables a self-onboarding concept for developers.

Suggestion to cover some topics for version 0.1:
1. Coding Style (PEP8) in idiomic python way
2. Testcases for every change
3. Use issue tracker to find open enhancement with a badge
4. Use PR to publish changes

**Comment by ExpDev07** [comment]
Would be awesome if you could submit a PR for this 😍

**Comment by Kilo59** [comment]
Can we adopt a formatter and/or [import sorter](https://github.com/timothycrosley/isort)?
My preference is [`black`](https://github.com/psf/black).

**Comment by ExpDev07** [comment]
Absolutely @Kilo59

**Comment by gribok** [comment]
I will submit a PR. Please assign issue to myself. 
@Kilo59 For formatter discussion, please raise another issue.

**Comment by Kilo59** [comment]
> I will submit a PR. Please assign issue to myself. 
> @Kilo59 For formatter discussion, please raise another issue.

The style guide, linter and formatter decisions need to be made  holistically. Otherwise they are liable to conflict.
