### ISSUE TITLE
Add Tallies for Regions

### ISSUE THREAD

**Issue by rmr1012** [ExpDev07/coronavirus-tracker-api#171]
Hi,

Thanks for the great work putting this together! 

I'm seeing some issues with some countries with provinces/states not having a total tally directly queryable. I've been doing the adding myself but that has been heavy on compute. (Missing China, Canada, Australia, and Cruise Ship)
Also, looks like the state-wide tallies also went away for some reason. For the US, now there's no easy way to get the total count and timeline for a state without adding it up from counties.

**Comment by ExpDev07** [comment]
Per JHU’s (our main data provider) announcement, they’ve decided to move away from province tracking and focus on countries as a whole, that’s why you see data missing. 

For your second question, yes, there is, try “/v2/locations?province=New%20York” and check the top level “latest”. It’ll have the latest of all counties in New York aggregated together. 

Go to the README file and check out our new Swagger documentation, you can test your requests directly there :).

**Comment by rmr1012** [comment]
I see, thanks!
Any chance to get timeline data for states?  Tried v2/locations?source=csbs&province=New%20York&timelines=1 but didn't see any timelines getting returned

**Comment by ExpDev07** [comment]
Unfortunately, CSBS doesn’t provide timeline data at the moment.

**Comment by rmr1012** [comment]
Got it. One last question, since JHU is tracking countries, seems like CA, AU, and CN still doesn't have country-wide tally
v2/locations?timelines=1&country_code=CA

**Comment by ExpDev07** [comment]
I can’t 100% tell you what’s going on in JHU’s mind, because they’re making some weird ass and random decisions, but I think they’re still working on the migration over, or that they just decided to exclusively don’t track provinces for U.S. Your example request does yield the total stats for Canada though, just look in the top-level latest JSON-object.

**Comment by rmr1012** [comment]
Got it, thanks a bunch!
