### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by potchangelo** [ExpDev07/coronavirus-tracker-api#173]
Thanks you for the API, I'm using on my project, COVID-19 Tracker app.
Website: https://covid-19-tracker-app.netlify.com
Github: https://github.com/potchangelo/covid-19-tracker

The site worked normally on the past days. But today I got API request error (from Mozilla Firefox console).

```
Cross-Origin Request Blocked: 
The Same Origin Policy disallows reading the remote resource at 
https://coronavirus-tracker-api.herokuapp.com/v2/locations. 
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

Do you have any solutions ?

**Comment by traderjosh** [comment]
Yes, same issue

![image](https://user-images.githubusercontent.com/15523421/77510781-70b7c500-6e67-11ea-818a-3293d433fdd0.png)

**Comment by davidsommer** [comment]
Same issue here, i'm doing a fetch in javascript:
Access to fetch at 'https://coronavirus-tracker-api.herokuapp.com/v2/locations?country_code=CH&timelines=1' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by ExpDev07** [comment]
Hello! I have enabled CORS. Please give it a few minutes for the changes to take effect.

**Comment by ExpDev07** [comment]
It is now enabled.

**Comment by davidsommer** [comment]
@ExpDev07  THX -> works perfectly again
