### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by pritampawade** [ExpDev07/coronavirus-tracker-api#174]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by ExpDev07** [comment]
Coming back up now.

**Comment by ExpDev07** [comment]
The cause has been fixed.

**Comment by pritampawade** [comment]
:( not working

**Comment by ExpDev07** [comment]
@pritampawade It is now :) The heroku was just overwhelmed with the initial amounts of requests so it took some time for it to catch up.
