### ISSUE TITLE
I have made Android App using this API

### ISSUE THREAD

**Issue by Ravipatel401** [ExpDev07/coronavirus-tracker-api#175]
I have develop simple Android Application using this API for public but still did not share yet, I want you to inform you people about this what should i do for further improvement and development any suggestion if we can launch for public or not ? 

I tried to find out contact details but could not seen anywhere so just trying to reach you people by creating issue, 

Please share your contact details so i can share more information on this,

**Comment by ExpDev07** [comment]
Feel free to reach me at discord at Marius Big Ounce#2997.

**Comment by Ravipatel401** [comment]
Please Check request sent on discord !
