### ISSUE TITLE
recovered timeline is empty for each feature

### ISSUE THREAD

**Issue by markus-bergelt** [ExpDev07/coronavirus-tracker-api#176]
Hi there unfortunately the recovered timeline is empty for each feature requesting the locations like this: https://coronavirus-tracker-api.herokuapp.com/v2/locations?timelines=1

![image](https://user-images.githubusercontent.com/58459623/77524966-8db0c000-6e88-11ea-961f-a464b12cc4ef.png)

**Comment by ExpDev07** [comment]
https://github.com/ExpDev07/coronavirus-tracker-api/issues/161
