### ISSUE TITLE
the https://coronavirus-tracker-api.herokuapp.com/ stopped working?

### ISSUE THREAD

**Issue by aramkoukia** [ExpDev07/coronavirus-tracker-api#182]
looks like there is an SSL error

**Comment by ExpDev07** [comment]
I'm not experiencing any errors? Could you provide a screenshot or something more?

**Comment by egbakou** [comment]
It works !

**Comment by aramkoukia** [comment]
here is what I get
![image](https://user-images.githubusercontent.com/7307404/77567201-0b260180-6e84-11ea-995e-d908165fb94c.png)

**Comment by ExpDev07** [comment]
Could be anything on your end too really, or just the heroku server acting up. It's a free instance, so if you're looking for 100% connection realability, you're better forking the repo and launching your own instance of it.

**Comment by somm-doe** [comment]
It's probably just your antivirus software, @aramkoukia.
