### ISSUE TITLE
A site based on Egypt's situation with charts/real time.

### ISSUE THREAD

**Issue by Hershef** [ExpDev07/coronavirus-tracker-api#185]
You can give it a visit on: https://egcorona.com

Includes a message telling people to just stay home.

Updates real time ( a check once per 10 seconds ) with nice charts included

Recovered timeline is dead due to the recent data source situation, so don't mind it, for now.

Thanks for creating this API.
Hopefully the numbers would hit zero soon.

**Comment by ExpDev07** [comment]
>  Hopefully the numbers would hit zero soon.

Indeed!

Best wishes from Norway.
