### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Abdirahiim** [ExpDev07/coronavirus-tracker-api#189]
It says "Internal Server Error" when I load it up

**Comment by ExpDev07** [comment]
I see it. Investigating right now.

**Comment by Abdirahiim** [comment]
Alright, thanks

**Comment by Abdirahiim** [comment]
Btw how did you configure the @all-contributors bot? I can't seem to get it to work

**Comment by ExpDev07** [comment]
Seems to be fixed now. Looks like JHU updated their dates and messed up but quickly fixed it?

**Comment by ExpDev07** [comment]
@Abdirahiim simply install the bot here https://allcontributors.org/.

**Comment by Abdirahiim** [comment]
I did but when I call for it it doesn't seem to respond or do a PR

**Comment by ExpDev07** [comment]
Hmm, that's odd. The documentation for it is at least here https://allcontributors.org/docs/en/bot/installation. I didn't follow any more steps than these.
