### ISSUE TITLE
CSBS does not provide timelines

### ISSUE THREAD

**Issue by jwillis0720** [ExpDev07/coronavirus-tracker-api#196]
https://github.com/ExpDev07/coronavirus-tracker-api/blob/573d45ee64faf8dcc4ef407e0a31b392dab87ed7/app/services/location/csbs.py#L26

I just want to make super dooper sure I'm not missing anything before I start storing this data. CSBS does indeed not report timeline data and only updates current. Requesting a timeline with CSBS source returns the same as not requesting a timeline and this is expected behavior. I'm now storing this data nightly in an AWS RDS instance, more to follow.

**Comment by ExpDev07** [comment]
@jwillis0720 yes, you're correct. They don't support recoveries nor timelines, only present data of confirmed and deaths.

**Comment by Kilo59** [comment]
Should we return a 4xx code for this? I'm inclined to think we should.

**Comment by ExpDev07** [comment]
@Kilo59 Possibly, but that's for another issue. Closing this.
