### ISSUE TITLE
Recovered Cases are empty

### ISSUE THREAD

**Issue by haxzie** [ExpDev07/coronavirus-tracker-api#198]
API response for Recovered cases are empty.
Checked in both
```
https://coronavirus-tracker-api.herokuapp.com/recovered
```
and 
```
https://coronavirus-tracker-api.herokuapp.com/all
```
both returns empty array.

### Sample response
```
{
   "last_updated":"2020-03-26T08:04:25.856718Z",
   "latest":0,
   "locations":[

   ],
   "source":"https://github.com/ExpDev07/coronavirus-tracker-api"
}
```

**Comment by Zrna** [comment]
+1 for empty recovered cases on https://coronavirus-tracker-api.herokuapp.com/all

**Comment by ExpDev07** [comment]
This is due to a bug in JHU’s (our data provider) file that lists data for recoveries. Once it gets fixed it should start working again.

**Comment by ExpDev07** [comment]
https://github.com/ExpDev07/coronavirus-tracker-api/issues/161
