### ISSUE TITLE
Getting multiple selected countries in a single query

### ISSUE THREAD

**Issue by dixoncheng** [ExpDev07/coronavirus-tracker-api#199]
Is it possible to get multiple selected countries in a single query?

```
eg /v2/locations?country_code=US,GB
```

**Comment by ExpDev07** [comment]
No, unfortunately not at the moment. You’ll have to make multiple requests and add them together.

**Comment by saifalfalah** [comment]
I would love this too! One request for several locations instead of having to send multiple requests.
