### ISSUE TITLE
A 404 Error

### ISSUE THREAD

**Issue by isratahm** [ExpDev07/coronavirus-tracker-api#2]
Hi- thank you so much for this! (Context I'm very much a beginner at this, but I thought I'd give it a go)

And I seemed to have followed all the instructions and have gotten everything set up. But since it's my first time I must have made some sort of error because I keep getting a 404.

Here is the exact error "GET / HTTP/1.1" 404 -

Would really appreciate it if you could help! Thanks (:

**Comment by ExpDev07** [comment]
There could be multiple reasons for this. You have to give more information like your OS, are you trying locally or deploying somewhere. Any errors in your console?

**Comment by isratahm** [comment]
Sorry for the lack of information! I am using MacOS Catalina, and am trying to deploy locally. 

I installed python, pip, pipenv, flask and then ran the lines below:

git clone https://github.com/ExpDev07/coronavirus-tracker-api.git
cd coronavirus-tracker-api
pipenv shell
pipenv install
Running / Development

flask run
Visit your app at http://localhost:5000
But when I try to visit the app, I get the 404 error. Currently no errors in the console until I try to visit the app. I do get a notification that says that I should run zsh.

Thank you so much for taking the time out to sort this with me!

**Comment by ExpDev07** [comment]
Oh, right. There's nothing at "/" (http://localhost:5000). The available endpoints are:
- http://localhost:5000/all
- http://localhost:5000/confirmed
- http://localhost:5000/deaths
- http://localhost:5000/recovered

These can be found in the "routes" folder, also note the __init__.py file in this folder as well. Hope this helped!

**Comment by isratahm** [comment]
You are legitimately amazing. It works! it was so simple! I'm hoping to run the data through Tableau (:
