### ISSUE TITLE
Add test coverage to testing

### ISSUE THREAD

**Issue by gribok** [ExpDev07/coronavirus-tracker-api#207]
To enforce test-driven development, let's measure test coverage via `Coverage.py`.
The result can be added to [Coveralls](https://coveralls.io/), which provides a free service for open source project and has a built-in integration in Travis-CI.
It would be possible to add a new quality gate into CI pipeline, that new code have to be covered with test cases.

**Comment by Kilo59** [comment]
Was going to suggest the same thing.
@gribok do you want to take this?

**Comment by gribok** [comment]
@Kilo59 Yes. Do we want to measure `statement` or `branch` coverage?

**Comment by Kilo59** [comment]
@gribok I would say `statement` but if you have a case for `branch` coverage I'm all ears.

**Comment by gribok** [comment]
> @gribok I would say `statement` but if you have a case for `branch` coverage I'm all ears.

Statement coverage sounds good. Let's try.
