### ISSUE TITLE
https://coronavirus-tracker-api.herokuapp.com/v2/latest "recovered" is 0

### ISSUE THREAD

**Issue by davidlsweeney** [ExpDev07/coronavirus-tracker-api#208]
Issue: at https://coronavirus-tracker-api.herokuapp.com/v2/latest "recovered" is 0, I do not think this should be 0.
![Capture](https://user-images.githubusercontent.com/35756043/77702578-bc13d400-701d-11ea-9cfa-402b4d75f378.PNG)

Was using this endpoint for a PyPortal Project and as of a day or two ago recovered would display total recovered cases but it is now 0.

**Comment by ExpDev07** [comment]
https://github.com/ExpDev07/coronavirus-tracker-api/issues/161
