### ISSUE TITLE
Argentina data not update

### ISSUE THREAD

**Issue by Pato2777** [ExpDev07/coronavirus-tracker-api#209]
Good job and thank you for share this
 i have a mini dashboard for calculate ratios and variabilities but the data not update today
in Argentina yesterday there were 117 and actually there are 0

thanks!

--

**Comment by ExpDev07** [comment]
I cannot reproduce?

https://coronavirus-tracker-api.herokuapp.com/v2/locations?source=jhu&country_code=AR
```json
{
  "latest": {
    "confirmed": 387,
    "deaths": 8,
    "recovered": 0
  },
  "locations": [
    {
      "id": 6,
      "country": "Argentina",
      "country_code": "AR",
      "country_population": 41343201,
      "province": "",
      "last_updated": "2020-03-26T23:33:06.544250Z",
      "coordinates": {
        "latitude": "-38.4161",
        "longitude": "-63.6167"
      },
      "latest": {
        "confirmed": 387,
        "deaths": 8,
        "recovered": 0
      }
    }
  ]
}
```

**Comment by Pato2777** [comment]
{
  "latest": {
    "confirmed": 387,  -------------------> 502
    "deaths": 8,
    "recovered": 0
  },
  "locations": [
    {
      "id": 6,
      "country": "Argentina",
      "country_code": "AR",
      "country_population": 41343201,
      "province": "",
      "last_updated": "2020-03-26T23:33:06.544250Z",
      "coordinates": {
        "latitude": "-38.4161",
        "longitude": "-63.6167"
      },
      "latest": {
        "confirmed": 387,  -------------------> 502
        "deaths": 8,
        "recovered": 0
      }
    }
  ]
}


timeline 


       "2020-03-17T00:00:00Z":68,
                  "2020-03-18T00:00:00Z":79,
                  "2020-03-19T00:00:00Z":97,
                  "2020-03-20T00:00:00Z":128,
                  "2020-03-21T00:00:00Z":158,
                  "2020-03-22T00:00:00Z":266,
                  "2020-03-23T00:00:00Z":301,
                  "2020-03-24T00:00:00Z":387,
                  "2020-03-25T00:00:00Z":387 ------------> 115
               }
            },

**Comment by ExpDev07** [comment]
Do you mean there's 502 confirmed cases? In that case, it shouldn't have decreased. All the API is doing is retrieving data from JHU. If numbers have changed, it's their doings.

**Comment by Pato2777** [comment]
Fixed tnx
