### ISSUE TITLE
Reimplementation of country_code - why?

### ISSUE THREAD

**Issue by Bost** [ExpDev07/coronavirus-tracker-api#210]
The reimplementation of the `country_code` function in the 73f02fb does at least 3 dictionary lookups for any input: 3 lookups in the best-case and 5 lookups in worst-case scenarios:

```python
                   # 1.                     # 2.
    if not country in is_3166_1 and country in synonyms:
        country = synonyms[country]     # 3.

    # Return code if country was found.
    if country in is_3166_1:            # 4.
        return is_3166_1[country]       # 5.
```
Where the original implementation does only 2 lookups in the best-case and only 4 lookups in worst-case scenarios:
```python
    if country in is_3166_1:             # 1.
        return is_3166_1[country]        # 2.  
    else:
        if country in synonyms:          # 2.
            synonym = synonyms[country]  # 3.
            return is_3166_1[synonym]    # 4.
        else:
            if verbose:
                print ("No country_code found for '" + country + "'. Using '" + default_code + "'")
            return default_code
```
To me it looks like the old implementation is more efficient, right?

Yea i know, the code gets optimized, dictionaries get cached, processor instructions reordered, etc. by some "magic". Either way this function gets computed quite a lot, and one cannot predict "magic"...  So then why such a change? Have you done any measurements?

**Comment by Bost** [comment]
Also, reuse or shadowing of variable or parameter names in general makes the code brittle. I.e. bugs get easily introduced when refactoring etc. I'm talking about the `country` variable here in our case.

**Comment by Bost** [comment]
On the other side we've got just 2 levels of nested if-else statements instead of 3. I see that. But 3 is not so much and it doesn't outweight the performance penalty, IMO.

**Comment by Bost** [comment]
Aaah, hello there https://github.com/ExpDev07/coronavirus-tracker-api/milestone/1

**Comment by ExpDev07** [comment]
Hello! Yes, my apologies! The initial change was to try and make it more readable, and in my head they seemed equal at the time. I've changed it again and this time, it should only do 3 lookups at max. Once when initially checking if country is found, if not, it looks it up in synonym, then a third time for retrieval.

**Comment by Bost** [comment]
Wait wait.
if the performance is a problem then we should map the synonyms straight to the country codes. Not to the ISO defined country names.

**Comment by ExpDev07** [comment]
@Bost I wouldn't really say it's a huge problem, but a solution could be something like

```python
country_codes = {
  "US": [ "United States of America, US, U.S." ]
}
```

Could that perhaps be more efficient?

**Comment by Bost** [comment]
... but in the 7ebcc175 we lost an important warning, so we don't know if there's yet another new synonym or a typo in country names. So that e.g. "Russija" gets mapped to "Others" and won't know about that. That's slightly sub-optimal so to say...

**Comment by Bost** [comment]
> @Bost I wouldn't really say it's a huge problem, but a solution could be something like
> 
> ```python
> country_codes = {
>   "US": [ "United States of America", "US", "U.S." ]
> }
> ```
> 
> Could that perhaps be more efficient?

Uhm, this way the keys and values of the dictionary must be at reversed at first and then a search in the list must be done. And I don't think we have that many lookups in the synonyms dictionary anyway. The most performant solution would be to use a straight mapping `synonym -> country_code` i think. (As I mentioned few minutes ago)

**Comment by ExpDev07** [comment]
>  so we don't know if there's yet another new synonym or a typo in country names

Ah yes, my bad. This fixes it: https://github.com/ExpDev07/coronavirus-tracker-api/pull/212 :). Thanks for notifying!

**Comment by ExpDev07** [comment]
> The most performant solution would be to use a straight mapping synonym -> country_code i think. (As I mentioned few minutes ago)

That would be a good solution yeah.

**Comment by Bost** [comment]
Solved in https://github.com/ExpDev07/coronavirus-tracker-api/pull/218
