### ISSUE TITLE
add county data source for (US only)

### ISSUE THREAD

**Issue by chovy** [ExpDev07/coronavirus-tracker-api#22]
https://sfc-project-files.s3.amazonaws.com/project-feeds/covid19_us_cases_us.json

**Comment by ExpDev07** [comment]
This looks like something which is a bit far off right now.

**Comment by chovy** [comment]
https://lionbridge.ai/datasets/coronavirus-datasets-from-every-country/

**Comment by JKSenthil** [comment]
I have created an api for county data: https://github.com/JKSenthil/coronavirus-county-api

Interestingly, both my and @ExpDev07 api use Python/Flask. Perhaps I can merge a county endpoint to this project? Shall I make a pull request?

**Comment by ExpDev07** [comment]
@JKSenthil There should be some discussions surrounding this and how it should be implemented. There is a basis for adding multiple datasources (see https://github.com/ExpDev07/coronavirus-tracker-api/tree/master/app/services/location). Then I'm thinking we'll add a query param to ``/v2/locations`` which allows you to define your data-source of choice. E.g: ``/v2/locations?source=jhu`` would mean the ``jhu`` service would be used to fetch the locations.

**Comment by JKSenthil** [comment]
That sounds good. I think that `/v2/locations` can default to the jhu source, and `/v2/locations?source=1point3acres` can be used to access the US county data.
