### ISSUE TITLE
Do we have any API specific to India ?

### ISSUE THREAD

**Issue by azeezgaa** [ExpDev07/coronavirus-tracker-api#225]

**Comment by Abdirahiim** [comment]
This API does have data from India or did you mean one specific to India

**Comment by azeezgaa** [comment]
Yes it does have a India details, I mean to say specific to india or state wise like we have for china or US ?

**Comment by Abdirahiim** [comment]
No, it doesn't have that kind of data

**Comment by Abdirahiim** [comment]
You can check it out here: http://coronavirus-tracker-api.herokuapp.com/v2/locations?country=india

**Comment by azeezgaa** [comment]
And one more question. I still dont see the recovered response is accurate do we have any work around for getting the correct recovered respnose ?

**Comment by Abdirahiim** [comment]
jhu dropped support for the recovered data

**Comment by azeezgaa** [comment]
Thank you
