### ISSUE TITLE
Recovered are not displayed

### ISSUE THREAD

**Issue by SergejYermakovich** [ExpDev07/coronavirus-tracker-api#227]

**Comment by d00mfish** [comment]
I have the same Problem. No Recovered numbers. Worldwide and in every country. That makes the whole situation a look lot more depressing :(

**Comment by Benjozork** [comment]
Please look at the pinned issue, @SergejYermakovich @d00mfish

**Comment by d00mfish** [comment]
Oh didnt see it. Thanks a lot
