### ISSUE TITLE
possible new problem with Country Codes

### ISSUE THREAD

**Issue by pizzavore** [ExpDev07/coronavirus-tracker-api#23]
I just noticed it this morning: 2020-03-11 14:14

It looks like some of the country_code fields are now set to "XX" .  The reason I noticed it now, is that Iran is set to "XX". I'm pretty sure it was correctly set to "IR" yesterday.  

 I can remap it locally in my code, I just wanted to give you a "heads up".  

Thanks again for everything!

**Comment by ExpDev07** [comment]
Thanks for the heads up. I’ll investigate, it’s probably just JHSU messing around, *again*.

**Comment by ameenpv** [comment]
May be [this is the reason for that glitch](https://github.com/CSSEGISandData/COVID-19/issues/504)

**Comment by ExpDev07** [comment]
@ameenpv That was indeed it. I have updated the country codes to reflect the new country names.
