### ISSUE TITLE
Android App for this API

### ISSUE THREAD

**Issue by pritampawade** [ExpDev07/coronavirus-tracker-api#230]
Hi, 
Check out my work developed using this library :)
[Android App]

Play store not allowing Corona related apps on play store :( that's why posting 3rd party download link

https://appsenjoy.com/download/bff9cf035d46ddd4a241f248a3741cc1.html

**Comment by Bost** [comment]
> Play store not allowing Corona related apps on play store 

@pritampawade well that's for a reason. There are a way too many criminals out there trying to scam people with all sorts of "Apps". No doubt you that, do you? So, please show us your source code. Thank you.
