### ISSUE TITLE
Great API! Building a small web app

### ISSUE THREAD

**Issue by ahmedfaaid** [ExpDev07/coronavirus-tracker-api#231]
Hey I am using your app to build a small [web app using Next.js and React](https://github.com/ahmedfaaid/covid-19-tracker).

I have a small issue. When querying data from /v2/locations, some countries return multiple data sets broken down by province/state. Some have one object which shows the overall stats for the country however Canada and China only returns province stats and no overall country stats in that route. Can there be a separate object added that only includes the total country stats?

**Comment by ExpDev07** [comment]
To get the total of a country, you can query with country_code and use the top-level “latest”, which sums all the provinces together. E.g for Canada: /v2/locations?country_code=CA

**Comment by clinkadink** [comment]
Great api, **many thanks for all your hard work**, it is appreciated. I too have the same question/suggestion ... like Ahmedfaaid has raised. I understand your reply, but this would not work when using timelines for each country, when there are multiple provinces. 

Example below shows 33 provinces, each with separate timelines - which makes it difficult to see growth over time for China (or any other country with multiple provinces):
https://coronavirus-tracker-api.herokuapp.com/v2/locations?country_code=CN&timelines=1

What would be great, is to have an option to have a total _dummy_ province, including the sum of all other provinces and the sum of all province timelines.

**Comment by ahmedfaaid** [comment]
Just like clinkadink says, it would be great to have an object with an empty string for province that returns all the cases for that country without having to make another get request to the country code route.

**Comment by ahmedfaaid** [comment]
Just an update, i just wrote code to basically create a new array with only unique country names and then handle the different provinces only when I query /v2/locations?country_code=CA.

I'll be closing this issue later.
