### ISSUE TITLE
Make all endpoints async

### ISSUE THREAD

**Issue by Kilo59** [ExpDev07/coronavirus-tracker-api#232]
To increase the throughput of the API we need to make our routes None blocking.

Methods and [dependencies](https://fastapi.tiangolo.com/async/#dependencies) used by the endpoints also need to be non-blocking (where possible).
This is probably the best place to start.

⚠️ Do not simply add `async` keyword to the current endpoints.

I will update this issue with details.

## Resources
https://www.encode.io/articles/hello-asgi
https://fastapi.tiangolo.com/async/#concurrency-and-async-await

**Comment by james-gray** [comment]
Hey @Kilo59, I've got a branch I can submit for this, but I don't have access rights to push my branch - would it be possible to be added as a collaborator? Thanks!

(CC @ExpDev07 )

**Comment by Kilo59** [comment]
You don't need to be a contributer to open a pull request

**Comment by james-gray** [comment]
https://github.com/ExpDev07/coronavirus-tracker-api/pull/256
