### ISSUE TITLE
Retrieving timelines by U.S. county

### ISSUE THREAD

**Issue by albertc44** [ExpDev07/coronavirus-tracker-api#233]
Is it possible to retrieve data by U.S. county by date? Based on a quick exploration it looks like the only date field is `last_updated`. Was thinking this query might allow me to pull data by date and by county: https://coronavirus-tracker-api.herokuapp.com/v2/locations?timelines=1&country_code=US&source=csbs

**Comment by Kilo59** [comment]
> Is it possible to retrieve data by U.S. county by date?

US County data is provided by the csbs source, which AFIAK does not breakdown it's data by date.
https://www.csbs.org/information-covid-19-coronavirus

**Comment by albertc44** [comment]
Gotcha. I've been using the NYT source in the interim (#224 )
