### ISSUE TITLE
Heroku application down?

### ISSUE THREAD

**Issue by cyenyxe** [ExpDev07/coronavirus-tracker-api#240]
At least during the last couple of hours, a timeout is triggered when trying to access the Heroku instance. See for example https://coronavirus-tracker-api.herokuapp.com/v2/sources

Could it have to do with #174 ?

**Comment by Kilo59** [comment]
Are you still having this problem?

**Comment by cyenyxe** [comment]
Yes, still the same. I have tried from different browsers and devices to make sure it's not a caching issue.
