### ISSUE TITLE
Generate requirements.txt files

### ISSUE THREAD

**Issue by gribok** [ExpDev07/coronavirus-tracker-api#244]
To ensure interoperability with other python package manager, it makes senses to generate `requirements.txt` and `requirements-dev.txt`.
`pipenv` provides capabilities to generate requirements-files for production and development-environment.
See https://pipenv.readthedocs.io/en/stable/advanced/#generating-a-requirements-txt

**Comment by Kilo59** [comment]
What's the benefit of this?
As you said anybody who wants to can generate them with `pipenv lock -r --dev > requirements.txt`

**Comment by gribok** [comment]
> @gribok
> Not saying I'm against it but, what's the benefit?
> As you said, anybody who wants to can generate requirements file with `pipenv lock -r --dev > requirements.txt`
> 
> 1. Won't having 2 sets of dependency/requirements files lead to confusion?
> 2. How do we ensure they stay in sync?

1. I'm more confused about `Pipefile`, if I worked always with `requirements.txt` inside a `virtuelenv`. 
    It provides capability to use desired package manager directly without workaround to export package list from `pipenv` first.
2. Same procedure as with update of `Pipefile`. Change requester have to update the `Pipfile.lock`.
    Additonally `requirements.txt` files have to be generated to PR. 
    Maybe, is it a topic to add into `CONTRIBUTION` guide.

**Comment by Kilo59** [comment]
I think there's 2 things we need in order for this to happen.
1. `generate-reqs` (or similar name) [`invoke` task](https://github.com/ExpDev07/coronavirus-tracker-api/blob/master/tasks.py) to generate the requirements files
2. pytest test or CI step that ensures that the requirements.txt and `Pipfile.lock` are in sync

**Comment by gribok** [comment]
> I think there's 2 things we need in order for this to happen.
> 
> 1. `generate-reqs` (or similar name) [`invoke` task](https://github.com/ExpDev07/coronavirus-tracker-api/blob/master/tasks.py) to generate the requirements files
> 2. pytest test or CI step that ensures that the requirements.txt and `Pipfile.lock` are in sync

Good point. I'm going to check it out.

**Comment by gribok** [comment]
Please check my PR.
