### ISSUE TITLE
Experiencing issues contacting the API, all was fine yesterday.

### ISSUE THREAD

**Issue by coenraadhuman** [ExpDev07/coronavirus-tracker-api#248]
![Screenshot from 2020-04-01 11-45-22](https://user-images.githubusercontent.com/20205514/78123455-789ada80-740e-11ea-870f-acce551be6b5.png)

![Screenshot from 2020-04-01 11-48-55](https://user-images.githubusercontent.com/20205514/78123669-d0394600-740e-11ea-833f-228f160fb924.png)

**Comment by Kilo59** [comment]
Are you still experiencing this?

**Comment by coenraadhuman** [comment]
Yes we are still experiencing the same issue.

**Comment by JoseMontero24** [comment]
Is the same for me, not working
![Error](https://user-images.githubusercontent.com/62922862/78173662-4771d880-7415-11ea-9617-5017afd8efd4.PNG)

**Comment by nguyandy** [comment]
Down for me as well :(

**Comment by ahmedfaaid** [comment]
I'm experiencing the same as well

**Comment by RcDevRIL** [comment]
Same here..!

Wassup @ExpDev07

**Comment by RcDevRIL** [comment]
Nevermind, it came back online on my side ! 🔥

**Comment by Kilo59** [comment]
My guess is the application cannot handle all of the incoming traffic. We are on the free tier of heroku, which means less computing power and poor monitoring features.
We have put off some of the performance optimizations that would greatly increase the number of requests we can process.

https://github.com/ExpDev07/coronavirus-tracker-api/milestone/1

If you are in the US you can try hitting another instance that is not as heavily used.
https://covid-tracker-us.herokuapp.com/

**Comment by Toxyl** [comment]
I've setup a mirror of the API that you can use as a fallback: https://cvtapi.nl/
