### ISSUE TITLE
Add docker compatibility

### ISSUE THREAD

**Issue by GabrielDS** [ExpDev07/coronavirus-tracker-api#251]
Hello everyone!!!

To get the benefit of run the api with one command (with isolation), how about add the dockerfile and docker-compose to this project?

Do you see some problem about this?

**Comment by Kilo59** [comment]
@GabrielDS someone started this process already, but seems to have abandoned it.
https://github.com/ExpDev07/coronavirus-tracker-api/pull/123

This would likely need to change to use FastAPI instead of Flask.
https://fastapi.tiangolo.com/deployment/#docker

**Comment by GabrielDS** [comment]
@Kilo59 Ok.. but the image "tiangolo/uvicorn-gunicorn-fastapi:python3.7" seems using python3.7 and not python3.8  (what is required according READ.ME)

**Comment by Kilo59** [comment]
@GabrielDS it shouldn't matter for a docker deployment

**Comment by GabrielDS** [comment]
@Kilo59  
Nice!! Do u think if we should create another pull request or wait for the pull request owner?

**Comment by Kilo59** [comment]
> @Kilo59
> Nice!! Do u think if we should create another pull request or wait for the pull request owner?

I would just create a new one.

**Comment by GabrielDS** [comment]
> > @Kilo59 Ok.. but the image "tiangolo/uvicorn-gunicorn-fastapi:python3.7" seems using python3.7 and not python3.8 (what is required according README.md)
> 
> @GabrielDS it shouldn't matter for a docker deployment

I tried run this image locally, but the pipenv is forcing to use python3.8.

**Comment by Kilo59** [comment]
It does not force you to use 3.8.
https://pipenv.readthedocs.io/en/latest/basics/#specifying-versions-of-python

**Comment by GabrielDS** [comment]
> It does not force you to use 3.8.
> https://pipenv.readthedocs.io/en/latest/basics/#specifying-versions-of-python

@Kilo59 
Thanks!! I never have used pipenv so i'm a bit newbie about it.

Ok.. Done! I created a pull request.
