### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by asportnoy** [ExpDev07/coronavirus-tracker-api#261]
The [API](https://coronavirus-tracker-api.herokuapp.com/) is currently returning "Application Error" from Heroku. Please get it back up.

![Screen Shot 2020-04-04 at 11 21 08 PM](https://user-images.githubusercontent.com/14863373/78466768-14f10580-76cb-11ea-91f9-c9a1f0681b32.png)
`

**Comment by assetcorp** [comment]
Seems to be working fine now.
