### ISSUE TITLE
Add logging to project

### ISSUE THREAD

**Issue by gribok** [ExpDev07/coronavirus-tracker-api#266]
How is about integrate of logging module to project, which could be controlled through config file with different logging level?
Maybe with a rotated logfile.

**Comment by Kilo59** [comment]
@gribok I should have been more specific. We do logging. We don't have a good way to filter and sort through the logs, especially if any significant time has passed.
We should probably log more things, but it won't do a lot of good if we can't easily look at and filter them.

**Comment by Kilo59** [comment]
I don't know much about the logging tools available on Heroku.
If anyone has experience with any of these let me know.

https://elements.heroku.com/addons

## Free Tier

1. https://elements.heroku.com/addons/logdna
2. https://elements.heroku.com/addons/timber-logging
3. https://elements.heroku.com/addons/sumologic
4. https://elements.heroku.com/addons/papertrail
5. https://elements.heroku.com/addons/sentinel-trails
6. https://elements.heroku.com/addons/logentries

## Paid Only

7. https://elements.heroku.com/addons/coralogix

**Comment by Kilo59** [comment]
I went ahead and added Timber-logging to the main Heroku deployment.
https://elements.heroku.com/addons/timber-logging

I don't know that it's THE BEST offering, I'd be happy to switch to something else.
The next time we have an issue it should be easier to search/filter through it.

There's still work to be done to add more logging around critical sections.

**Comment by Kilo59** [comment]
`timber-logging` maxed out at 1 GB of free log storage and rather than roll over the logs,  it just prevents me from doing anything until I pay for more storage. ☹️ 
If there's a way to fix this it's not obvious to me. Going to try a different service.

**Comment by Kilo59** [comment]
Should use Sentry's ASGI Middleware for Error tracking.
https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/asgi.py#L59

**Comment by Kilo59** [comment]
Implemented in #311
