### ISSUE TITLE
'URL: https://coronavirus-tracker-api.herokuapp.com/v2/locations?timelines=1' Doesn't work anymore.

### ISSUE THREAD

**Issue by Superblazer** [ExpDev07/coronavirus-tracker-api#275]
Hello, this url has suddenly stopped working for me. Returns an Heroku Application error if I check the url on the browser.

**Comment by Toxyl** [comment]
It was down for me too, but it is back.

**Comment by brim-borium** [comment]
It's currently down again. Seems like a timeout issue?

**Comment by HashJar** [comment]
The response size with flag **timelime=1** is 1.2 MB, and 66 KB without it.

**Comment by zamponotiropita** [comment]
The endpoints are down again. Tested also https://coronavirus-tracker-api.herokuapp.com/ and https://coronavirus-tracker-api.herokuapp.com/all

**Comment by Kilo59** [comment]
> The response size with flag **timelime=1** is 1.2 MB, and 66 KB without it.

Thanks for reminding me about the response size. Going to add GZIP compression.
