### ISSUE TITLE
Deaths number for Germany less than yesterday. Should be impossible. JHU Problem?

### ISSUE THREAD

**Issue by pingustar** [ExpDev07/coronavirus-tracker-api#277]
Unless people are reborn in Germany :D this shouldnt be possible. Is this inconsistency coming from the JHU data or a problem with the API?

**Germany:**
```
"4/10/20": 2767,
"4/11/20": 2736
```

(using the following endpoint: https://coronavirus-tracker-api.herokuapp.com/deaths)

**Comment by Toxyl** [comment]
That's a JHU problem as you can see here: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

**Comment by pingustar** [comment]
Thank you. 

Will open issue there.

Closed.
