### ISSUE TITLE
Incorrect country_codes

### ISSUE THREAD

**Issue by majidkorai** [ExpDev07/coronavirus-tracker-api#28]
I have noticed, that two digit country codes (country_code) for some countries are not correct, api is returning `XX` instead of actual country code. Example countries Iran, South Korea etc.

**Comment by majidkorai** [comment]
Just went through the code. turns out that problem is in the country codes utility. `country_code` mappings for some countries doesn't resolve to their names. Its not only `Iran` and `South Korea`, there are few other countries as well for which codes are not resolved.

**Comment by ExpDev07** [comment]
Should be fixed now. This is unfortunately a symptom of JSU constantly changing their naming conventions...
