### ISSUE TITLE
2  Superfulous comma in country data

### ISSUE THREAD

**Issue by PRRH** [ExpDev07/coronavirus-tracker-api#284]
I know this is very minor.
country Code:-Korea, South
in Netherlands province: Bonair,Sint

**Comment by Bost** [comment]
@PRRH what exactly do you mean? How to repeat your test case?

**Comment by PRRH** [comment]
*********** These are the only 2 inconsistancies in
                                         all of the countries where extra comma's appear
                                    This is extract for data downloaded from V1 All

      {
        "country": "Korea, South",                              ******Korea,
                                                                      ______
        "country_code": "KR",
        "province": "",
        "coordinates": {
          "lat": "36.0",
          "long": "128.0"
       



      {
        "country": "Netherlands",
        "country_code": "NL",
        "province": "Bonaire, Sint Eustatius and Saba",        *****Bonair,
                                                                    _______
        "coordinates": {
          "lat": "12.1784",
          "long": "-68.2385"
        },
        "history": {

**Comment by Bost** [comment]
The content of the `country` and `province` comes from the JHU repo, more precisely from the columns `Province/State` and `Country/Region` in their the csv files. As you can see on lines [93 - 111](https://github.com/ExpDev07/coronavirus-tracker-api/blob/375794e1a17fb955282bc148cff62ee873e89ff4/app/services/location/jhu.py#L93-L111) we just pass it on. (IOW garbage in, garbage out.) BTW exactly this problem: "JHU uses non standard country names" is the reason why there's the `country_code` in this API service. You're strongly advised to use it.

@Kilo59 IMO we can close this issue.

**Comment by PRRH** [comment]
> The content of the `country` and `province` comes from the JHU repo, more precisely from the columns `Province/State` and `Country/Region` in their the csv files. As you can see on lines [93 - 111](https://github.com/ExpDev07/coronavirus-tracker-api/blob/375794e1a17fb955282bc148cff62ee873e89ff4/app/services/location/jhu.py#L93-L111) we just pass it on. (IOW garbage in, garbage out.) BTW exactly this problem: "JHU uses non standard country names" is the reason why there's the `country_code` in this API service. You're strongly advised to use it.
> 
> @Kilo59 IMO we can close this issue.

Thanks for you reply.
It was only a passing comment.
