### ISSUE TITLE
Timeline json formatting

### ISSUE THREAD

**Issue by ChuckVanzant** [ExpDev07/coronavirus-tracker-api#298]
Is it possible to modify, or as an option, write the timeline json format to be the following? It might be easier to parse. Thanks!

{
  "location": {
    "id": 39,
    "country": "Norway",
    "country_code": "NO",
    "country_population": 5009150,
    "province": "",
    "county": "",
    "last_updated": "2020-03-21T06:59:11.315422Z",
    "coordinates": { },
    "latest": { },
    "timelines": {
      "confirmed": {
        "latest": 1463,
        **"timeline": [
          {"date":"2020-03-16T00:00:00Z","count": 1333},
          {"date":"2020-03-17T00:00:00Z","count": 1463}
        ]**
      },
      "deaths": { },
      "recovered": { }
    }
  }
}

**Comment by Kilo59** [comment]
This is the first I've seen anyone complain about the difficulty in parsing the response.
Why is this better?

**Comment by ChuckVanzant** [comment]
Don't know how others are parsing but. I'm using the .NET System.Text.Json namespace, JsonSerializer.Deserialize<> to dump the response body into objects derived from a sample representation of the response body. The current structure expects each date in a timeline to be a separate class. My suggestion is to format a timeline as a list of timeline class objects, each with date and count properties. For instance, a few of the derived objects are shown below:
```
    public class Timeline
    {
        public DateTime date { get; set; }
        public int count { get; set; }
    }
    public class Confirmed
    {
        public int latest { get; set; }
        public IList<Timeline> timeline { get; set; }
    }
    public class Deaths
    {
        public int latest { get; set; }
        public IList<Timeline> timeline { get; set; }
    }
    public class Recovered
    {
        public int latest { get; set; }
        public IList<Timeline> timeline { get; set; }
    }
    public class Timelines
    {
        public Confirmed confirmed { get; set; }
        public Deaths deaths { get; set; }
        public Recovered recovered { get; set; }
    }``
```

**Comment by Kilo59** [comment]
I still don't understand what the benefit to doing this is, but it could be worth considering for any new versions of the api.
I don't expect we will be changing the format of existing responses as that would break lots of apps that rely on the API.

**Comment by ChuckVanzant** [comment]
I had some reformatting code that reformatted the response body so I could deserialize it into the needed destination objects but the reformatting took nearly 2 minutes to execute. I ended up skipping the timeline feature via your API and I am now directly downloading the CSV file from the NYT site and processing it which only takes a near negligible amount of time.

**Comment by WinformsWizard** [comment]
Here is a simple way to do in C# using Newtonsoft.Json
```C#
/*
* By WinformsWizard
*/
using System;
using System.Net.Http;
using Newtonsoft.Json;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            HttpClient client = new HttpClient();

            string resultjson = client.GetAsync
            ("http://coronavirus-tracker-api.herokuapp.com/v2/latest")
            .Result.Content.ReadAsStringAsync().Result;

            Data data = JsonConvert.DeserializeObject<Data>(resultjson);

            System.Console.WriteLine(data.latest.ToString());

        }
    }
    public class Data {
       
       public Latest latest {get; set; }
       
        public class Latest {
            
            public int confirmed { get; set; }
            public int deaths { get; set; }
            public int recovered { get; set;}

            public override string ToString() {
                string result = "";
                result += $"Confirmed: {confirmed} ";
                result += $"Deaths: {deaths} ";
                result += $"Recovered {recovered}";

                return result;
            }   
        }
    }
}

```
