### ISSUE TITLE
Date sorting

### ISSUE THREAD

**Issue by windsolace** [ExpDev07/coronavirus-tracker-api#3]
Hey, want to check if 2/11/20 and 2/12/20 appearing before 2/2/20 is intended

**Comment by ExpDev07** [comment]
I’m gonna check it out. Think I have to parse the dates and do some sorting. For now, you can just sort them client side, it’s not really the biggest deal.

**Comment by ExpDev07** [comment]
This isn't a bug. Since it's a JSON object and not an array, the order returned by the code will not be preserved.
