### ISSUE TITLE
[BUG] Encoding of coordinates, latitude and longitude, differ between CSBS & NYT

### ISSUE THREAD

**Issue by ChuckVanzant** [ExpDev07/coronavirus-tracker-api#301]
The encoding of coordinates, latitude and longitude, differ between these two sources:

NYT - v2/locations?source=nyt&timelines=true" - properties encoded as numbers
"coordinates":{"latitude":0,"longitude":0}

CSBS - v2/locations?source=csbs - properties encoded as strings
"coordinates":{"latitude":"40.71455","longitude":"-74.00714"}

This causes a deserializing exception when using the same destination classes.
Workarounds are to use a cloned set of destination classes or to replace all NYT instances of {"latitude":0,"longitude":0} with {"latitude":"0","longitude":"0"} since they are all zeroes anyway as long as they will always be zeroes.

**Comment by Kilo59** [comment]
I agree this is probably worth fixing. I'd be happy to accept a pull request to address this.

**Comment by Kilo59** [comment]
As per issue #303 the values are returned as `null` not numbers.
Still worth fixing  of course 😄
