### ISSUE TITLE
improve installation section: no pipenv

### ISSUE THREAD

**Issue by ret394** [ExpDev07/coronavirus-tracker-api#302]
responsive, performant website. thanks a lot.

https://github.com/ExpDev07/coronavirus-tracker-api#installation
only issue is `install pipenv`, it over-complicates stuff for little benefit. use python 3.x with venv module.

feel free to @ / contact me for more info at https://github.com/ret394/jubilant-broccoli/issues.

thanks. have a nice day. keep up the good work. 👍

[ret394](https://github.com/ret394)

**Comment by Kilo59** [comment]
@ret394 you are free to ignore the use of `pipenv` and use `venv` and the `requirements` files directly.
