### ISSUE TITLE
Long in location

### ISSUE THREAD

**Issue by elsonjose** [ExpDev07/coronavirus-tracker-api#31]
The long variable cant be used in java as an identifier because its a keyword. Please change it to lng.

**Comment by ExpDev07** [comment]
If you’re talking about JSON deserialization to a POJO, you should have a way to set an alternative way. Example:
‘’’java
@JsonProperty(“long”)
private long longitude;’’’

Changing it in the API will lead to very many apps breaking, which I don’t want to do.

**Comment by elsonjose** [comment]
Thanks.

**Comment by ExpDev07** [comment]
No problem! :)

**Comment by elsonjose** [comment]
Anyway i completed the project. Feel free to contribute and suggest changes. https://github.com/elsonjose/Covid19

**Comment by ExpDev07** [comment]
Good job!
