### ISSUE TITLE
[UPDATE ISSUE]

### ISSUE THREAD

**Issue by elizaan** [ExpDev07/coronavirus-tracker-api#320]
API data is being updated lately these days. More than 24 hours have been occurred but still no update of historical data

**Comment by PRRH** [comment]
Has the updating finsihed??

**Comment by elizaan** [comment]
> Has the updating finsihed??

not been updated yet! data till 23 June still

**Comment by Kilo59** [comment]
> > Has the updating finsihed??
> 
> not been updated yet! data till 23 June still

Have you checked the source data to see if it has been updated yet?

**Comment by PRRH** [comment]
Every thing now OK
