### ISSUE TITLE
Access to application

### ISSUE THREAD

**Issue by PRRH** [ExpDev07/coronavirus-tracker-api#323]
**Describe the bug**
A clear and concise description of what the bug is. Please include timestamps and HTTP status codes.
If possible include the [httpie](https://httpie.org/) or `curl` request and response.
Please include the verbose flag. `-v` 

**To Reproduce**
`httpie/curl` request to reproduce the behavior:
1. Getting Italy data at `v2/locations/IT` gives a 422.
2. Expected to same data as `/v2/locations?country_code=IT`
2. See httpie request & response below

**Expected behavior**

**Screenshots or Requests**
If applicable, add screenshots or `httpie/curl`requests to help explain your problem.
```sh
$ http GET https://coronavirus-tracker-api.herokuapp.com/v2/locations/IT -v                                                                                                                                                            
GET /v2/locations/IT HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: coronavirus-tracker-api.herokuapp.com
User-Agent: HTTPie/2.0.0



HTTP/1.1 422 Unprocessable Entity
Connection: keep-alive
Content-Length: 99
Content-Type: application/json
Date: Sat, 18 Apr 2020 12:50:29 GMT
Server: uvicorn
Via: 1.1 vegur

{
    "detail": [
        {
            "loc": [
                "path",
                "id"
            ],
            "msg": "value is not a valid integer",
            "type": "type_error.integer"
        }
    ]
}
```

**Additional context**
Does the other instance at https://covid-tracker-us.herokuapp.com/ produce the same result?

**Comment by PRRH** [comment]
https://coronavirus-tracker-api.herokuapp.com/
returns application error
becoming annoying

**Comment by PRRH** [comment]
No sooner leaving a comment application up & running.

**Comment by PRRH** [comment]
Did not last for more than 2 mins then
APPLICATION ERROR !!!!!https://coronavirus-tracker-api.herokuapp.com/

**Comment by Sajantoor** [comment]
Says application error for me also if I go to anything under or fetch from "https://coronavirus-tracker-api.herokuapp.com/". When will this be fixed?

**Comment by Kilo59** [comment]
@Sajantoor 
If 100% availability is an issue for you I suggest deploying the application yourself or using this US-based version.
https://covid-tracker-us.herokuapp.com/
