### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by traderjosh** [ExpDev07/coronavirus-tracker-api#329]
Cannot access the API again. Previous user brought this bug up below. Error is to do with CORS, but he mentioned Heroku is down. 

> Hello, thanks for this fantastic work. Since yesterday I can't access to the data. I've been trying with the followings URL:
> 
> https://covid-tracker-us.herokuapp.com/v2/locations?source=nyt&county=los%20angeles or https://coronavirus-tracker-api.herokuapp.com/v2/locations/224 and after a while Application Error appears.
> 
> How can I help to fix this?
> 
> ![image](https://user-images.githubusercontent.com/64545348/89124575-788b1400-d4ae-11ea-976b-ab79b0e72e85.png)
> 
> Thanks

**Comment by traderjosh** [comment]
it's back up

**Comment by orestis-z** [comment]
I'm getting 503. Is the API still maintained?

**Comment by Kilo59** [comment]
> I'm getting 503. Is the API still maintained?

You've made this same comment on 3 different issues.

There answer is yes but we need to do some work to minimize memory usage. We are using the free tier of Heroku and it keeps bumping up against its memory limit.

Probably I'll be changing the default behavior to only retrieve the latest `x` days of history by default.

**Comment by web-sys1** [comment]
Same here.
![Screenshot_Monday 1602526106000](https://user-images.githubusercontent.com/61905565/95777951-cd79b080-0ccf-11eb-8c4c-7aa050312d06.png)
