### ISSUE TITLE
[BUG] "/v2/sources" API endpoint returns 503 http status code

### ISSUE THREAD

**Issue by vyahello** [ExpDev07/coronavirus-tracker-api#331]
GET request on https://coronavirus-tracker-api.herokuapp.com/v2/sources API endpoint returns 503 http status code:
```
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: 
https://coronavirus-tracker-api.herokuapp.com/v2/sources
```
Do we support `/v2/sources` endpoint ?

**Comment by orestis-z** [comment]
Is the API still maintained?

**Comment by wobsoriano** [comment]
api dead

**Comment by Kilo59** [comment]
https://github.com/ExpDev07/coronavirus-tracker-api/issues/329#issuecomment-706770078

**Comment by web-sys1** [comment]
#332
