### ISSUE TITLE
API not updating

### ISSUE THREAD

**Issue by paolotamag** [ExpDev07/coronavirus-tracker-api#34]
I spent some time to build a visualization with your API. However for today it still shows 0 increase in Italy and in other countries. Are you guys aware of any issue?

**Comment by Abdirahiim** [comment]
I don't think it's the API but it's the data source, the timestamp in the API looks like it updates

**Comment by cfchenr** [comment]
Same issue

**Comment by ExpDev07** [comment]
The API retrieves data from the  2019 Novel Coronavirus (nCoV) Data Repository, provided by JHU CCSE on an hourly basis. This repository, however, updates only once a day.
