### ISSUE TITLE
[BUG] Unable to access the site. Error 503 (Service Unavailable) 

### ISSUE THREAD

**Issue by carlshan** [ExpDev07/coronavirus-tracker-api#340]
**Describe the bug**
Hitting the v2 API at the `https://covid-tracker-us.herokuapp.com` backend is yielding a 503 Server Error.

I've seen the other issues that have raised this problem in the past and know that there may be some work in progress to reduce memory usage to prevent hitting the Heroku free tier limits.

Raising this issue as I recently ran into it again today.

Context: I hit this API every 2 weeks to generate some internal + external reports & infographics about COVID for my company.

**Comment by carlshan** [comment]
Update: literally 15 minutes after I posted the bug above, the API came back up. I'm leaving the Issue open for now so that it flags this issue for a maintainer to see, and perhaps inform prioritization against whether to do anything to prevent future downtime.

**Comment by web-sys1** [comment]
Duplicate issue **[BUG] Unable to access the site. Error 503 (Service Unavailable)** (note that #332 was originally opened in October year).

**Comment by Kilo59** [comment]
Sorry guys. 

I made some experimental changes to the US version of the site awhile ago to try to reduce memory usage but it seems to have had the opposite effect and so it is now much more unstable than the EU version and goes down several times a day. 

This all despite the fact that it gets a lot less traffic 😬. 

Thanks for the details, I'll either fix it or revert the changes within the week.

**Comment by carlshan** [comment]
Thanks @Kilo59.

**Comment by Kilo59** [comment]
I've reverted the US mirror to use the same code as the EU one.

LMK if it seems to behave better or worse over the next few days.

I still need to find a memory profiler that works with FastAPI/Starlette, and then I can fix or rate-limit the problematic endpoints.

**Comment by marianopeck** [comment]
Could someone please tell me the existing mirrors so that I can try which one seems more stable? Because neither https://covid-tracker-us.herokuapp.com or https://coronavirus-tracker-api.herokuapp.com seem stable to me. I am getting 50x errors on both

**Comment by Kilo59** [comment]
@marianopeck what routes are you hitting?

**Comment by marianopeck** [comment]
Hi @Kilo59 I hitting once https://coronavirus-tracker-api.herokuapp.com/v2/locations?source=jhu&timelines=false and then, once per location, I hit  'https://coronavirus-tracker-api.herokuapp.com/v2/locations/{1}?source=jhu&timelines=false' . 
My problem is always with the latter. And there are 2 situations I get:

1) 500 Internal Server Error response
2) 200 OK but with empty contents! 

With the US version (same URLs as above but US flavor) I was getting an "Application Error" HTML response 

Any idea?

**Comment by Kilo59** [comment]
@marianopeck I would bet the first request is actually the one that causes the memory issue on the tiny heruko instances.
And your subsequent requests are hitting just as the application is trying to recover.

But that's just a guess before I've had a chance to do some memory profiling.

**Comment by marianopeck** [comment]
@Kilo59 thanks for the insights. Do you know if there are other bigger heroku instances without this issue? I am asking because my usage of this is for a online demo/presentation and I fear it would fail during it... 
If I can be of any help with this let me know..all I can offer is to run my script and keep you posted.

**Comment by Kilo59** [comment]
There was someone awhile ago that was ruining it on some more robust infrastructure awhile ago (I think maybe Digital Ocean). 
I can't look it up easily from my phone. 

If you are concerned about a failure during a demo I would recommend you run it locally. Either directly or using Docker.

**Comment by marianopeck** [comment]
Thanks @Kilo59 for the ideas. Yeah, I thought about running locally with Docker. I will see how far can I get with that one.
Also, if by any chance, whenever you are back with the computer, you find that other digital ocean server, please let me know!
