### ISSUE TITLE
Change in data source

### ISSUE THREAD

**Issue by Matthiasjee** [ExpDev07/coronavirus-tracker-api#35]
There's been a change in the data source folder naming. Because of that the latest updated date in history is 3/9/20.

**Comment by ExpDev07** [comment]
It's not. The JSON is just not sorted (because it's a dict and not an array), so if you actually go through all the history, you'll see there's data for 3/11/20 for example. Can you point to the data source folder naming please?

**Comment by Matthiasjee** [comment]
Sorry, my bad, didn't look closely. Thank you for your work!
