### ISSUE TITLE
Using your api for a simple visualization

### ISSUE THREAD

**Issue by majidkorai** [ExpDev07/coronavirus-tracker-api#37]
Hi, 

I am used your api to create a simple visualization [here](https://github.com/majidkorai/corona-viz)

**Comment by thalen** [comment]
I made one as well. [here](https://github.com/thalen/corona-inspector)

**Comment by RamPrasadMeenavalli** [comment]
I am using this for showing the numbers with an SharePoint webpart - [https://github.com/RamPrasadMeenavalli/react-covid19-tracker](https://github.com/RamPrasadMeenavalli/react-covid19-tracker)
