### ISSUE TITLE
Values for March 12 are duplicates of March 11 for certain countries

### ISSUE THREAD

**Issue by pizzavore** [ExpDev07/coronavirus-tracker-api#38]
I haven't gone through all of the data yet, but I can confirm that for Italy:  The values for March 12 are the same as March 11, for all three metrics: confirmed, deaths, recovered.

For Spain, the same is true for confirmed and recovered, but for deaths the value on March 12th is 55, which is one more than March 11th (54), but 55 is incorrect for March 12th, the correct value should be somewhere around 84. 

I assume this is due to more changes from the JHU team.  But the weird value for Spanish deaths (55 vs 84) is harder to explain. Perhaps the JHU data has some manually entered data and it was just  an entry error?

Anyway, thanks again for all the work you have done on this tracker!

**Comment by ExpDev07** [comment]
> I assume this is due to more changes from the JHU team. But the weird value for Spanish deaths (55 vs 84) is harder to explain. Perhaps the JHU data has some manually entered data and it was just an entry error?
If there's duplicate values for both dates, then JHU put duplicate values. Very little I can do. You can manually check the data by looking in these CSV files: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series.

**Comment by pizzavore** [comment]
You are correct, the JHU files have the duplicate values as well. Hopefully they will correct them  over the next day or two.

Thanks!
