### ISSUE TITLE
Latest confirmed, deaths, and recoveries are all 0

### ISSUE THREAD

**Issue by john-bauer** [ExpDev07/coronavirus-tracker-api#39]
Using it here https://coronavirus-tracker-demo.netlify.com/

**Comment by RashikCh** [comment]
Seems to be an issue with the API. No code changes publicly so I'm not sure.

**Comment by ExpDev07** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/686

**Comment by john-bauer** [comment]
Ok, thanks for clarifying and thanks for making this!

**Comment by ExpDev07** [comment]
No problem, should probably keep it open so others see it and close when JHU fixes their *swears* data *again*.

**Comment by RashikCh** [comment]
That is disappointing to see, I might start parsing the csv files for daily_reports myself but from looking at the other issues those may not be reliable too?

**Comment by ExpDev07** [comment]
> That is disappointing to see

Indeed. Would really expect to see a higher standard for a repo with 8k+ stars. Sudden changes in naming conventions, changing names of files, data mixup, and now this. It'll probably be fixed soon though.

**Comment by ExpDev07** [comment]
Seems to be fixed now!

**Comment by chovy** [comment]
It’s still broken.
