### ISSUE TITLE
Problem with the api

### ISSUE THREAD

**Issue by TheApphiver** [ExpDev07/coronavirus-tracker-api#4]
We are currently using this api for an app to track coronavirus, the issue is that the api returns 0 and empty arrays, we want to know if it is something wrong with the server or your updating the directories.

**Comment by ExpDev07** [comment]
This is an issue with the third party the API is retrieving data from. I’ll get it fixed myself in a couple of hours.

**Comment by TheApphiver** [comment]
Ok thank you so much

**Comment by ExpDev07** [comment]
It should now be all fixed and working.
