### ISSUE TITLE
Format breaking change in 002e1af - Why?

### ISSUE THREAD

**Issue by Bost** [ExpDev07/coronavirus-tracker-api#41]
002e1af `History now returns a string-int pair and not string-string`

And I had the impression you understand that format breaking changes must be avoided!!! Oh how silly was I!
:angry:

**Comment by Bost** [comment]
I'm unstarring your repo.

**Comment by ExpDev07** [comment]
It’s not a breaking change. It was initially a bug, and people would convert the string to a int in their code, which still works without change.

**Comment by Bost** [comment]
Oh yea, it worked so well that I had to release a hot fix at 4:42 in the morning containing a commit titled:

[Fix format breaking change in ExpDev07/coronavirus-tracker-api](https://github.com/Bost/corona_cases/commit/a00eeddcba482ef437e52607acfce6d14515e1e1)

Thank you sooo, much. You know, when writing this issue I thought you gonna reply something along the lines:

> Oh I haven't anticipated my consumers code can be strongly typed. I see vars type of int and string are **NOT** type-compatible, (even if they carry the same information), I apologize

But no, you're denying the problem.

Well then farewell.

**Comment by ExpDev07** [comment]
I do apologize for any inconveniences. I will make sure it doesn’t happen again in the future.
