### ISSUE TITLE
Querying locations for a specific province takes time

### ISSUE THREAD

**Issue by neelr** [ExpDev07/coronavirus-tracker-api#42]
I'll make a PR, but when you query for a province in locations, its a large array, so it would be easier to return a object with province and if null then country

**Comment by ExpDev07** [comment]
Could you give an example of object returned?

**Comment by neelr** [comment]
instead of 
```
[
{... specificProvinceData}
]
```

it would be 

```
{
      proviceOrCountry:{... specificProvinceData}
}
```
