### ISSUE TITLE
date format in history

### ISSUE THREAD

**Issue by pdobsan** [ExpDev07/coronavirus-tracker-api#46]
Thank you for your software and service.

May I suggest to use the ISO 8601 date format (`yyyy-mm-dd`)  in the key string of `history`.  While parsing the current format not a big deal using the the ISO standard has some benefits. I am sure your current and potential users are from all over the word. Using the ISO format the interpretation  of the response of your service would be easier for everyone.

During conversion into the ISO format you might be able to do some error checking since as the country names show your data source is far form stable for obvious reasons.

Yes, I am aware of the complain about the recent change in `history`.  Despite of that  I still suggest the ISO date format while you are at the cleaning up the `history` array.

**Comment by ExpDev07** [comment]
This is a major breaking change so introducing this at the current endpoints will not be possible. I’m working on a /v2/ where I’m going to do be doing this.

**Comment by pdobsan** [comment]
On Sun, Mar 15, 2020 at 09:22:17AM -0700, ExpDev wrote:
> This is a major breaking change so introducing this at the current
> endpoints will not be possible. I’m working on a /v2/ where I’m going
> to do be doing this.

Sure, doing that for /v2/ is fine. When do you expect /v2/ to be ready?

**Comment by ExpDev07** [comment]
Introduced in /v2/. See https://github.com/ExpDev07/coronavirus-tracker-api/blob/master/README.md for examples and documentation.
