### ISSUE TITLE
No module named "flask_cors" found

### ISSUE THREAD

**Issue by QYQSDTC** [ExpDev07/coronavirus-tracker-api#48]
![image](https://user-images.githubusercontent.com/15608306/76709503-30b94b00-66cd-11ea-9ede-03728b7ec2be.png)
When I was trying to run it locally, this error came, I did all the previous steps successfully.

**Comment by ExpDev07** [comment]
Have you installed pipenv globally?

After that, you must make sure to be in the pipenv shell when executing the commands. You can enter the shell by typing “pipenv shell” in the project directory, then to install deps, write “pipenv install”.

**Comment by QYQSDTC** [comment]
Yes, I did that before. After I quit the shell and restart it again, it's working !!
