### ISSUE TITLE
Coronavirus data missing for Finland

### ISSUE THREAD

**Issue by PRRH** [ExpDev07/coronavirus-tracker-api#488]
Having downloaded the data from the beginning of the pandemic, I have notices in the last 10 days or so than Finland data are zero. No data from the 15th January to present day. (15-16 January would normally be zero as it is a weekend)
just thought I would point it out.
KEEP UP THE GOOD WORK AND THANKS.

**Comment by ExpDev07** [comment]
Odd, but not much we can do with that. It needs to be resolved by JHU (https://github.com/CSSEGISandData/COVID-19).
