### ISSUE TITLE
Getting results by country

### ISSUE THREAD

**Issue by eldan-dex** [ExpDev07/coronavirus-tracker-api#54]
I'm trying to use the API on an embedded device without enough RAM to hold the entire result and filter it. Is it possible to add an option to only get stats for a specific country or other filtering options?

**Comment by ExpDev07** [comment]
I am working on that rn for v2, which will hopefully be done some time today. It is currently not possible without consuming the whole dataset and filtering on your client.

**Comment by assetcorp** [comment]
Yeah, I think this feature would really be helpful. Can't wait for v2.

**Comment by sebamed** [comment]
Any news on this topic?

**Comment by ExpDev07** [comment]
@sebamed I have indeed implemented this in /v2/ now, there are just some final adjustments and design decisions.
