### ISSUE TITLE
Can the API return a fatten list of data?

### ISSUE THREAD

**Issue by altezza04** [ExpDev07/coronavirus-tracker-api#55]
I am using the this API, and it's great! Thank again.
However  is it possible to have  another endpoint of all combined Confirmed, Recovered and Deaths in a single object sort by country, it seem that JSON we got now is getting a bit big now, and country , coordinates, province, info are duplicated, a combined data may save a bit of download time. For example a endpoint like: /all_fattened

{
locations
--coordinates
--country
--province
--confirmed
----latest
----history
--deaths
----latest
----history
--recovered
----latest
----history
}

thanks!!

**Comment by ExpDev07** [comment]
This is exactly what I’m working on right now for v2! Will hopefully be done some time today.

**Comment by Sem1084** [comment]
Maybe add scopes as optional query: /all?scope=recovered%20confirmed%20deaths

**Comment by ExpDev07** [comment]
@Sem1084 yes, something like that shouldn’t be too hard to implement.

**Comment by sagarkarira** [comment]
Hey, @ExpDev07 thanks for the API. 

I've made this [command line tracker](https://github.com/sagarkarira/coronavirus-tracker-cli) using your API. 

I am also exposing flattened JSON of all countries here: 
[https://corona-stats.online/?format=json](https://corona-stats.online/?format=json)
if this good enough format for @altezza04 to use.

**Comment by altezza04** [comment]
> Hey, @ExpDev07 thanks for the API.
> 
> I've made this [command line tracker](https://github.com/sagarkarira/coronavirus-tracker-cli) using your API.
> 
> I am also exposing flattened JSON of all countries here:
> https://corona-stats.online/?format=json
> and also country wise https://corona-stats.online/Italy?format=json
> if this good enough format for @altezza04 to use.
Awesome! that's prefect, thanks! @sagarkarira @ExpDev07 
btw, that's my site https://chinavirus.live/
