### ISSUE TITLE
Store data in DB

### ISSUE THREAD

**Issue by ufo56** [ExpDev07/coronavirus-tracker-api#60]
Hi

I would like to store this data in e.g influxdb , but i can't figure out how.

Why? Because i would like to draw some graphs with Grafana.
I understand that i can use this https://grafana.com/grafana/plugins/simpod-json-datasource to query that heroku url but it would be nice to store data i think :)

**Comment by ExpDev07** [comment]
Yes, that is possible. Just sync the database with the JSON data, like hourly or something. People have done it.

**Comment by Sem1084** [comment]
Doesn't JHU update daily?

**Comment by ExpDev07** [comment]
@Sem1084 yeah, but you don’t exactly 100% know at what time JHU updates their data, so you’ll be better off just syncing every hour or so. If you want to save more resources, I guess you could do it once every 6 hours as well.
