### ISSUE TITLE
just a simple question why do I need to install it on my computer ?

### ISSUE THREAD

**Issue by NatiBerko** [ExpDev07/coronavirus-tracker-api#62]
cant I just use the links:
https://coronavirus-tracker-api.herokuapp.com/    all/confirmed/etc' ?
like some kind of web service ?

why In the read me there is the installation part ?

**Comment by ExpDev07** [comment]
Two reasons:
- you want to contribute to the source code or modify it; and/or
- you want to host the API yourself for faster speeds, more control, etc.

**Comment by NatiBerko** [comment]
Thank you for your quick answer ! got it...
