### ISSUE TITLE
duplicate entries

### ISSUE THREAD

**Issue by pingustar** [ExpDev07/coronavirus-tracker-api#63]
china, us, and others have a couple dozen of multiple entries.

**Comment by ExpDev07** [comment]
I can not seem to find them, can you give an example of a duplicated entry?

**Comment by pingustar** [comment]
@ExpDev07 

![image](https://user-images.githubusercontent.com/7262066/76896832-dec22200-6892-11ea-98db-a2a6878ef384.png)

does this help?

**Comment by ExpDev07** [comment]
Well, yes. Remember that a location doesn't necessarily represent each country, Multiple locations can have the same "country", what differs per location is the "province". For example:

```json
[
  {
    "country": "US",
    "province": "California"
  },
  {
    "country": "US",
    "province": "Texas"
  }
]
```

**Comment by pingustar** [comment]
ah I see. Thank you. 

So to get the accumulated amounts I have to sum up the 'latest' and 'history' value I guess, or is there an enpoint I am missing?

**Comment by ExpDev07** [comment]
@pingustar Currently, if you want to get the current/latest confirmed cases for a the United States, you can do something like this:

```javascript
// locations = locations array under "confirmed".
var latest = locations.filter(loc => loc.country_code === 'US').reduce((a, b) => a.latest + b.latest, 0)```

When /v2/ of the API releases, you will be able to query specific countries and locations, however, at the moment, you have to do this processing client-side unless you setup your own proxy-server that calls the API.

**Comment by pingustar** [comment]
thank you, appreciate it :)

**Comment by ExpDev07** [comment]
Closing. Feel free to open it again or create a new issue if you have any more questions :).

**Comment by pingustar** [comment]
@ExpDev07 do you have by any chance another one of those magic lines of code for me.

I am trying to accumulate the history data for each day to create statistics on how each country compares in terms of spread per day

**Comment by ExpDev07** [comment]
On my phone rn, it’s gonna be a bit more complicated, but it’s just a matter of adding all the timelines of your country’s locations together.
