### ISSUE TITLE
Add testcases for baseline testing app

### ISSUE THREAD

**Issue by gribok** [ExpDev07/coronavirus-tracker-api#64]
Let's add some testcases for unittesting of help function, like `date.is_date` and integration testcases for api endpoints, like `/deaths`.

I will try to provide a testsuite for testing of baseline to avoid breaking changes.

Next step could be to setup a `Travis CI` chain for auto-checking of every PR.
Let me know, if I can help.

**Comment by ExpDev07** [comment]
I will be pushing /v2/ soon which introduces new core code and features. Once that's good I'd love your help to start implementing test cases 👍

**Comment by gribok** [comment]
Pushed my changes via PR. Check it out and let me know. 👍

**Comment by gribok** [comment]
I am gonna to close the isse. Testsuite introduced.
