### ISSUE TITLE
Update interval

### ISSUE THREAD

**Issue by dducted** [ExpDev07/coronavirus-tracker-api#7]
Hi there,

I have just one quick question. How often does the API update? Right now its showing 79570 while https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6 shows 80421.

**Comment by ExpDev07** [comment]
If you look at the data link repository, there have been some questions why the numbers differ from JSU’s dashboard and repository. It’s not by a lot, but some. I’d rather go and ask there.

To answer your question: it updates every time the JSU’s repository updates (follow link under Data in README.md).

**Comment by bjarkimg** [comment]
There is a 1 day lag on this data vs the archis dashboard, JSU desision I believe.

**Comment by ExpDev07** [comment]
There you have it :). Thanks, @bjarkimg !

**Comment by ExpDev07** [comment]
@all-contributors add @bjarkimg for question.
