### ISSUE TITLE
I'm using your api

### ISSUE THREAD

**Issue by luizhfraraujo** [ExpDev07/coronavirus-tracker-api#70]
Hi! Thanks for your API.
Im using to build a Ionic app. 
site: https://ionic-coronavirus-tracker.netlify.com/
Repo: https://github.com/luizhfraraujo/ionic-coronavirus-tracker

**Comment by ExpDev07** [comment]
Really good job! Looks minimal and clean, and is fast.

**Comment by rohandoesjava** [comment]
Nice!
