### ISSUE TITLE
Add population data 

### ISSUE THREAD

**Issue by martiL** [ExpDev07/coronavirus-tracker-api#71]
Great Job

It would be nice if there is an endpoint to get the population data of all provinces. So It's easy to show the infection rate (cases/population). I use your API for my dashboard -> https://corona-data.netlify.com/

I found a CSV file, maybe you can include it in your API ( I think the last year with a population greater than 0.0 would be good enough -> maybe merge it with the JHU CCSE)?

`
{
  "locations": [
    {
      "id": 0,
      "country": "Thailand",
      "population": 1037238,  
`

**gist:**
https://gist.github.com/pascalwhoop/a38a70f1fc60711856ca2e6fea79e4e3

**data source**
https://data.worldbank.org/indicator/SP.POP.TOTL?end=2016&start=2016&view=bar

**link to CSV**
http://api.worldbank.org/v2/en/indicator/SP.POP.TOTL?downloadformat=csv

Btw: there is a GitHub organization "OpenCovid19
" which tries to provide an API -> https://github.com/open-covid19

**Comment by Turreted** [comment]
I'd like to start working on this, just a few questions before I start:

a) would you like this to be a separate endpoint, or an extension of the locations endpoint?
b) should this be on a per-country basis, or should I do it in terms of each district provided by Johns Hopkins?
c) should users be able to query for the population in a district or just the infections per capita?

**Comment by ExpDev07** [comment]
> a) would you like this to be a separate endpoint, or an extension of the locations endpoint?

No, it should be apart of the ``Location`` object. Possibly something like:
```python
@property
def population(self):
    """
    Gets the population of this location.
    """
    // return the population for this location.
    pass
```

> b) should this be on a per-country basis, or should I do it in terms of each district provided by Johns Hopkins?

Not a 100% sure about this. The easiest would just to provide population at country-level, but people will ask for province and possibly county-level too.

>  c) should users be able to query for the population in a district or just the infections per capita?

Not required.

**Comment by Turreted** [comment]
@ExpDev07 Sorry for taking so long. The changes can be found at pull request #188.

I also wasn't able to test this on my computer, so you should probably verify that it works before merge.
