### ISSUE TITLE
Is there possible to provide the timelines for countries?

### ISSUE THREAD

**Issue by alex644715** [ExpDev07/coronavirus-tracker-api#74]
Thank you for your works. Now I can get the timeline for each location, but it's not convenient way that gather all the info to analysis the timelines of each country. So can you provide an API for timelines of each country?

**Comment by ExpDev07** [comment]
With some magic, you can easily achieve this through some magic. First, fetch all the locations for your desired country with timelines added, e.g U.S.A:
```http
GET /v2/locations?country_code=US&timelines=true``

Now you have to add and sum all the timelines together at date-level. E.g:

Arizona's ``2020-03-17T00:00:00Z: 100`` + California's  ``2020-03-17T00:00:00Z: 200`` = USA's ``2020-03-17T00:00:00Z: 300`. You have to do this for all the locations and dates though.

**Comment by alex644715** [comment]
That's cool, thank you~

**Comment by ExpDev07** [comment]
It is essentially what I would do if I were to add the info. Maybe in the future there‘ll be a /countries endpoint which will do this for you, however, at the current moment I just wanna focus on fine-graining the API.

**Comment by alex644715** [comment]
I found the loading speed of US is too slow......

**Comment by ExpDev07** [comment]
I am running one free instance of Heroku which explains why it’s slow sometimes, the speed will improve if you host your own version.

**Comment by Kilo59** [comment]
@alex644715 It seems like the issue is resolved. If not reply here or open a new issue.
