### ISSUE TITLE
1 day lag with JHU CSSE Data

### ISSUE THREAD

**Issue by mploux** [ExpDev07/coronavirus-tracker-api#75]
Hello !

Thanks a lot for this API, it is exactly what I was looking for.
It seems that there is a lot of lag and the data is always one day behind. 
Is there a way to fix it and be up to date ?

Thanks again !

**Comment by ExpDev07** [comment]
It is up to date with a potential one hour delay with JHU CSSE’s timeline CSV file.

**Comment by marbysneaker** [comment]
having this same issue, it looks like world's latest confirms keeps pulling 197145 the whole day while John Hopkins data have updated several times and are now up to 214894.

**Comment by Bost** [comment]
> It is up to date with a potential one hour delay with JHU CSSE’s timeline CSV files.

@mploux The data stays in the cache for max 3600 seconds = 1 hour:
https://github.com/ExpDev07/coronavirus-tracker-api/blob/75eaed76fc26be64fbffe6999be24208c3665b8d/app/services/location/jhu.py#L30
https://github.com/ExpDev07/coronavirus-tracker-api/blob/75eaed76fc26be64fbffe6999be24208c3665b8d/app/services/location/jhu.py#L96

@marbysneaker No it works fine:
```
18 Mar 2020 @corona_cases_bot  Worldwide      /zz    /zzz
Day 57
Confirmed 214915      +17770 
Sick      122869  57% +14469 
Recovered  83313  39%  +2473 
Deaths      8733   4%   +828  See mortality rate
Closed     92046  43%  +3301 = recovered + deaths

/world   /about   /references   /<country>   /list   /feedback
```
See for yourself here https://t.me/corona_cases_bot

The ticket can be closed.

**Comment by mploux** [comment]
Hello,
The API is in fact up to date with JHU CSSE’s timeline CSV files, but it has one day lag.
Look here: https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6
You can clearly see more up to date data.
Any ideas on how we could get up to date data ?

Thanks

**Comment by ExpDev07** [comment]
By switching data source.

**Comment by mploux** [comment]
@ExpDev07 Hello, I'm back with some news and a solution.
Witch branch are you watching to get the data on [CSSEGISandData /
COVID-19](https://github.com/CSSEGISandData/COVID-19) ?
If you are looking at the `master` branch it's normal that the data is behind by a day as this branch is updated only once a day.
The correct branch to watch is the `web-data` branch https://github.com/CSSEGISandData/COVID-19/tree/web-data , on this branch the data is updated every hour or so. Is there any way to watch this branch and therefore have up to date data with this awesome API ? 
Thanks !

**Comment by ExpDev07** [comment]
@mploux I'll look into it, feel free to submit a PR.
