### ISSUE TITLE
Add record date to data

### ISSUE THREAD

**Issue by donpdonp** [ExpDev07/coronavirus-tracker-api#77]
Looking at  CSSEGISandData/COVID-19  and it looks like date-named csv files. It would be helpful if the json returned from the heroku app included the date of the file used to create the json. Right now its unattributed and if someone caches this data, its hard to say if its up to date or not. thanks! 

Also, I'm using your api to feed an irc chat bot that announces when the case count increases for our area. This is a great service thanks much!

**Comment by ExpDev07** [comment]
At the moment, we're getting *all* our data from just these three files: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series. The last updated in that case would be the most recent date in every location's timeseries.

**Comment by donpdonp** [comment]
sigh, we just dont know what the date of every location's last update is. what about simply putting the date of fetching the csv? that'd be something. i feel its important because these json files always live longer than one expects and if im doing a simple 'curl heroku/latest.json' im going to want to know the date *of that data file*, which is currently unknown.

the schema already has {location => } so adding a new top level entry like "date" => "2020-03-18" woundt break existing clients.

**Comment by ExpDev07** [comment]
> the schema already has {location => } so adding a new top level entry like "date" => "2020-03-18" woundt break existing clients.

That's what I was thinking of working on right now.
