### ISSUE TITLE
Created something with your api

### ISSUE THREAD

**Issue by MM-coder** [ExpDev07/coronavirus-tracker-api#88]
https://github.com/MM-coder/coronavirus-wallpaper

Created an application that sets your wallpaper with the latest coronavirus stats from your API

**Comment by ExpDev07** [comment]
Nice work! Using it myself :).

**Comment by MM-coder** [comment]
Cheers!

**Comment by rohandoesjava** [comment]
You should add it so that it displays the time at which the information was updated, that would be a nice feature.

**Comment by MM-coder** [comment]
Feel free to leave that as an issue on the repo
