### ISSUE TITLE
Can you set up Gzip Compression on the request?

### ISSUE THREAD

**Issue by dwalks12** [ExpDev07/coronavirus-tracker-api#9]
It would be nice to have Gzip compression on the request if possible

**Comment by ExpDev07** [comment]
Is that really necessary? The data returned is like 300kbs (with below < 200ms on my connection) uncompressed when hitting ``/all``. I can look into getting it added.

**Comment by dwalks12** [comment]
Not really just more so for page performance scores with google

**Comment by ExpDev07** [comment]
You can setup Gzip compression if you host the API yourself :). I'm running free heroku :/.
